before:
  hooks:
    - go mod tidy
builds:
  -
    main: ./cmd/nitro
    ldflags:
      - -w -X main.build={{.Version}}
    env:
      - CGO_ENABLED=0
      - GOEXPERIMENT=boringcrypto
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  -
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      amd64: 64bit
      386: 32bit
      arm: ARM
      arm64: ARM64
      darwin: macOS
      linux: Linux
      windows: Windows
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^wip:'
      - '^chore:'
      - '^refactor:'
