fs = require 'fs'

cases = []
css = fs.readFileSync 'output.css', 'utf8'
css = css.substring css.indexOf '.container'

classes = [...css.matchAll /^(\S+?)\s*\{(.+?)\}/gms]

tests = []
for c in classes
  [_, name, body] = c
  continue unless name.startsWith '.'
  name = name
    .substring 1
    .replace /\\\./g, '.'
  lines = body
    .trim()
    .split ';'
    .map (x) -> x.trim()
    .filter (x) -> if x then yes else no
    .map (x) ->
      [l, r] = x.split /\s*:\s*/, 2
      l + ':' + r
  rule = lines.join ';'

  tests.push "  expect(c('#{name}')).toEqual('#{rule}')"

  begin = '''
  //
  // DO NOT EDIT THIS FILE DIRECTLY!
  // Generated by tools/tailwind
  //

  import { stylize as c } from './css'

  it('style should match tailwind', () => {
  '''

  end = '''
  })
  '''

  ts = [begin, ...tests, end].join '\n'

fs.writeFileSync '../../web/src/css.test.ts', ts, 'utf8'

