
import { stylize as c } from './css'

it('style should match tailwind', () => {
  expect(c('bg-ui-foreground')).toEqual('background-color:var(--ui-foreground)')
  expect(c('bg-ui-background')).toEqual('background-color:var(--ui-background)')
  expect(c('bg-ui-accent')).toEqual('background-color:var(--ui-accent)')
  expect(c('bg-ui-accent-darker')).toEqual('background-color:var(--ui-accent-darker)')
  expect(c('bg-ui-accent-dark')).toEqual('background-color:var(--ui-accent-dark)')
  expect(c('bg-ui-accent-dark-alt')).toEqual('background-color:var(--ui-accent-dark-alt)')
  expect(c('bg-ui-accent-primary')).toEqual('background-color:var(--ui-accent-primary)')
  expect(c('bg-ui-accent-secondary')).toEqual('background-color:var(--ui-accent-secondary)')
  expect(c('bg-ui-accent-tertiary')).toEqual('background-color:var(--ui-accent-tertiary)')
  expect(c('bg-ui-accent-light')).toEqual('background-color:var(--ui-accent-light)')
  expect(c('bg-ui-accent-lighter')).toEqual('background-color:var(--ui-accent-lighter)')
  expect(c('bg-ui-accent-lighter-alt')).toEqual('background-color:var(--ui-accent-lighter-alt)')
  expect(c('bg-ui-neutral-dark')).toEqual('background-color:var(--ui-neutral-dark)')
  expect(c('bg-ui-neutral-primary')).toEqual('background-color:var(--ui-neutral-primary)')
  expect(c('bg-ui-neutral-primary-alt')).toEqual('background-color:var(--ui-neutral-primary-alt)')
  expect(c('bg-ui-neutral-secondary')).toEqual('background-color:var(--ui-neutral-secondary)')
  expect(c('bg-ui-neutral-secondary-alt')).toEqual('background-color:var(--ui-neutral-secondary-alt)')
  expect(c('bg-ui-neutral-tertiary')).toEqual('background-color:var(--ui-neutral-tertiary)')
  expect(c('bg-ui-neutral-tertiary-alt')).toEqual('background-color:var(--ui-neutral-tertiary-alt)')
  expect(c('bg-ui-neutral-quaternary')).toEqual('background-color:var(--ui-neutral-quaternary)')
  expect(c('bg-ui-neutral-quaternary-alt')).toEqual('background-color:var(--ui-neutral-quaternary-alt)')
  expect(c('bg-ui-neutral-light')).toEqual('background-color:var(--ui-neutral-light)')
  expect(c('bg-ui-neutral-lighter')).toEqual('background-color:var(--ui-neutral-lighter)')
  expect(c('bg-ui-neutral-lighter-alt')).toEqual('background-color:var(--ui-neutral-lighter-alt)')
})
