import { stylize as c } from './css'

it('should translate arbitrary values', () => {
  expect(c('w-[117px]')).toEqual('width:117px')
  // TODO
  // expect(c('grid-cols-[1fr_500px_2fr]')).toEqual('grid-template-columns:1fr 500px 2fr')
  // expect(c("bg-[#bada55]")).toEqual('--tw-bg-opacity:1;background-color:rgb(186 218 85 / var(--tw-bg-opacity)')
})

it('should translate color opacity', () => {
  expect(c('bg-indigo-500/75')).toEqual('--tw-bg-opacity:0.75;background-color:rgb(99 102 241 / var(--tw-bg-opacity))')
  expect(c('bg-black/75')).toEqual('--tw-bg-opacity:0.75;background-color:rgb(0 0 0 / var(--tw-bg-opacity))')
  expect(c('bg-white/75')).toEqual('--tw-bg-opacity:0.75;background-color:rgb(255 255 255 / var(--tw-bg-opacity))')
  expect(c('bg-accent-300/75')).toEqual('--tw-bg-opacity:0.75;background-color:rgb(var(--ui-accent-300) / var(--tw-bg-opacity))')
  // TODO
  // expect(c('grid-cols-[1fr_500px_2fr]')).toEqual('grid-template-columns:1fr 500px 2fr')
  // expect(c("bg-[#bada55]")).toEqual('--tw-bg-opacity:1;background-color:rgb(186 218 85 / var(--tw-bg-opacity)')
})

it('should translate stripes', () => {
  expect(c('bg-stripes-blue')).toEqual('background-color:rgb(96 165 250/.1);background-image:linear-gradient(135deg,rgb(59 130 246/.5) 10%,transparent 0,transparent 50%,rgb(59 130 246/.5) 0,rgb(59 130 246/.5) 60%,transparent 0,transparent);background-size:7.07px 7.07px')
  expect(c('bg-stripes-accent')).toEqual('background-color:rgb(var(--ui-accent-400)/.1);background-image:linear-gradient(135deg,rgb(var(--ui-accent-500)/.5) 10%,transparent 0,transparent 50%,rgb(var(--ui-accent-500)/.5) 0,rgb(var(--ui-accent-500)/.5) 60%,transparent 0,transparent);background-size:7.07px 7.07px')
})

it('should translate accent colors', () => {
  expect(c('bg-accent-300')).toEqual('--tw-bg-opacity:1;background-color:rgb(var(--ui-accent-300) / var(--tw-bg-opacity))')
})

it('should translate negative values', () => {
  expect(c('-m-1')).toEqual('margin:-0.25rem')
  expect(c('-mx-1')).toEqual('margin-left:-0.25rem;margin-right:-0.25rem')
  expect(c('-my-1')).toEqual('margin-top:-0.25rem;margin-bottom:-0.25rem')
  expect(c('-mt-1')).toEqual('margin-top:-0.25rem')
  expect(c('-mr-1')).toEqual('margin-right:-0.25rem')
  expect(c('-mb-1')).toEqual('margin-bottom:-0.25rem')
  expect(c('-ml-1')).toEqual('margin-left:-0.25rem')
  expect(c('-inset-1')).toEqual('top:-0.25rem;right:-0.25rem;bottom:-0.25rem;left:-0.25rem')
  expect(c('-inset-1/2')).toEqual('top:-50%;right:-50%;bottom:-50%;left:-50%')
  expect(c('-inset-x-1')).toEqual('left:-0.25rem;right:-0.25rem')
  expect(c('-inset-y-1')).toEqual('top:-0.25rem;bottom:-0.25rem')
  expect(c('-inset-y-1/2')).toEqual('top:-50%;bottom:-50%')
  expect(c('-inset-x-1/2')).toEqual('left:-50%;right:-50%')
  expect(c('-top-1')).toEqual('top:-0.25rem')
  expect(c('-right-1')).toEqual('right:-0.25rem')
  expect(c('-bottom-1')).toEqual('bottom:-0.25rem')
  expect(c('-left-1')).toEqual('left:-0.25rem')
  expect(c('-top-1/2')).toEqual('top:-50%')
  expect(c('-right-1/2')).toEqual('right:-50%')
  expect(c('-bottom-1/2')).toEqual('bottom:-50%')
  expect(c('-left-1/2')).toEqual('left:-50%')
  expect(c('-z-10')).toEqual('z-index:-10')
  expect(c('-order-1')).toEqual('order:-1')
  expect(c('-translate-x-1')).toEqual('--tw-translate-x:-0.25rem;transform:translate(var(--tw-translate-x), var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y))')
  expect(c('-translate-y-1')).toEqual('--tw-translate-y:-0.25rem;transform:translate(var(--tw-translate-x), var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y))')
  expect(c('-translate-x-1/2')).toEqual('--tw-translate-x:-50%;transform:translate(var(--tw-translate-x), var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y))')
  expect(c('-translate-y-1/2')).toEqual('--tw-translate-y:-50%;transform:translate(var(--tw-translate-x), var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y))')
  expect(c('-rotate-1')).toEqual('--tw-rotate:-1deg;transform:translate(var(--tw-translate-x), var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y))')
  expect(c('-skew-x-1')).toEqual('--tw-skew-x:-1deg;transform:translate(var(--tw-translate-x), var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y))')
  expect(c('-skew-y-1')).toEqual('--tw-skew-y:-1deg;transform:translate(var(--tw-translate-x), var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y))')
  expect(c('-scale-50')).toEqual('--tw-scale-x:-.5;--tw-scale-y:-.5;transform:translate(var(--tw-translate-x), var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y))')
  expect(c('-scale-x-50')).toEqual('--tw-scale-x:-.5;transform:translate(var(--tw-translate-x), var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y))')
  expect(c('-scale-y-50')).toEqual('--tw-scale-y:-.5;transform:translate(var(--tw-translate-x), var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y))')
  expect(c('-indent-1')).toEqual('text-indent:-0.25rem')
  expect(c('-scroll-m-1')).toEqual('scroll-margin:-0.25rem')
  expect(c('-scroll-mx-1')).toEqual('scroll-margin-left:-0.25rem;scroll-margin-right:-0.25rem')
  expect(c('-scroll-my-1')).toEqual('scroll-margin-top:-0.25rem;scroll-margin-bottom:-0.25rem')
  expect(c('-scroll-mt-1')).toEqual('scroll-margin-top:-0.25rem')
  expect(c('-scroll-mr-1')).toEqual('scroll-margin-right:-0.25rem')
  expect(c('-scroll-mb-1')).toEqual('scroll-margin-bottom:-0.25rem')
  expect(c('-scroll-ml-1')).toEqual('scroll-margin-left:-0.25rem')
  expect(c('-hue-rotate-30')).toEqual('--tw-hue-rotate:hue-rotate(-30deg);filter:var(--tw-blur) var(--tw-brightness) var(--tw-contrast) var(--tw-grayscale) var(--tw-hue-rotate) var(--tw-invert) var(--tw-saturate) var(--tw-sepia) var(--tw-drop-shadow)')
  expect(c('-backdrop-hue-rotate-30')).toEqual('--tw-backdrop-hue-rotate:hue-rotate(-30deg);-webkit-backdrop-filter:var(--tw-backdrop-blur) var(--tw-backdrop-brightness) var(--tw-backdrop-contrast) var(--tw-backdrop-grayscale) var(--tw-backdrop-hue-rotate) var(--tw-backdrop-invert) var(--tw-backdrop-opacity) var(--tw-backdrop-saturate) var(--tw-backdrop-sepia);backdrop-filter:var(--tw-backdrop-blur) var(--tw-backdrop-brightness) var(--tw-backdrop-contrast) var(--tw-backdrop-grayscale) var(--tw-backdrop-hue-rotate) var(--tw-backdrop-invert) var(--tw-backdrop-opacity) var(--tw-backdrop-saturate) var(--tw-backdrop-sepia)')
  expect(c('-space-x-1')).toEqual('--tw-space-x-reverse:0;margin-right:calc(-0.25rem * var(--tw-space-x-reverse));margin-left:calc(-0.25rem * calc(1 - var(--tw-space-x-reverse)))')
  expect(c('-space-y-1')).toEqual('--tw-space-y-reverse:0;margin-top:calc(-0.25rem * calc(1 - var(--tw-space-y-reverse)));margin-bottom:calc(-0.25rem * var(--tw-space-y-reverse))')
})