import {
  AcceptIcon,
  AcceptMediumIcon,
  AccessibiltyCheckerIcon,
  AccessLogoIcon,
  AccountActivityIcon,
  AccountBrowserIcon,
  AccountManagementIcon,
  AccountsIcon,
  ActionCenterIcon,
  ActivateOrdersIcon,
  ActivityFeedIcon,
  AddBookmarkIcon,
  AddEventIcon,
  AddFavoriteFillIcon,
  AddFavoriteIcon,
  AddFriendIcon,
  AddGroupIcon,
  AddHomeIcon,
  AddIcon,
  AddInIcon,
  AddLinkIcon,
  AddNotesIcon,
  AddOnlineMeetingIcon,
  AddPhoneIcon,
  AddReactionIcon,
  AddSpaceAfterIcon,
  AddSpaceBeforeIcon,
  AddToIcon,
  AddToShoppingListIcon,
  AddWorkIcon,
  AirplaneIcon,
  AirplaneSolidIcon,
  AirTicketsIcon,
  AlarmClockIcon,
  AlbumIcon,
  AlbumRemoveIcon,
  AlertSettingsIcon,
  AlertSolidIcon,
  AlignCenterIcon,
  AlignHorizontalCenterIcon,
  AlignHorizontalLeftIcon,
  AlignHorizontalRightIcon,
  AlignJustifyIcon,
  AlignLeftIcon,
  AlignRightIcon,
  AlignVerticalBottomIcon,
  AlignVerticalCenterIcon,
  AlignVerticalTopIcon,
  AllAppsIcon,
  AllAppsMirroredIcon,
  AllCurrencyIcon,
  AltTextIcon,
  AmazonWebServicesLogoIcon,
  AnalyticsQueryIcon,
  AnalyticsReportIcon,
  AnalyticsViewIcon,
  AnchorLockIcon,
  AndroidLogoIcon,
  AnnotationIcon,
  ApacheIvyLogo32Icon,
  ApacheMavenLogoIcon,
  ArchiveIcon,
  ArchiveUndoIcon,
  AreaChartIcon,
  ArrangeBringForwardIcon,
  ArrangeBringToFrontIcon,
  ArrangeByFromIcon,
  ArrangeSendBackwardIcon,
  ArrangeSendToBackIcon,
  ArrivalsIcon,
  ArrowDownRight8Icon,
  ArrowDownRightMirrored8Icon,
  ArrowTallDownLeftIcon,
  ArrowTallDownRightIcon,
  ArrowTallUpLeftIcon,
  ArrowTallUpRightIcon,
  ArrowUpRight8Icon,
  ArrowUpRightIcon,
  ArrowUpRightMirrored8Icon,
  ArticlesIcon,
  AscendingIcon,
  AspectRatioIcon,
  AssessmentGroupIcon,
  AssessmentGroupTemplateIcon,
  AssetLibraryIcon,
  AssignIcon,
  AssignPolicyIcon,
  AsteriskIcon,
  AsteriskSolidIcon,
  AttachIcon,
  AustralianRulesIcon,
  AutoDeploySettingsIcon,
  AutoEnhanceOffIcon,
  AutoEnhanceOnIcon,
  AutoFillTemplateIcon,
  AutoFitContentsIcon,
  AutoFitWindowIcon,
  AutoHeightIcon,
  AutomateFlowIcon,
  AutoRacingIcon,
  AwayStatusIcon,
  BackgroundColorIcon,
  BackIcon,
  BacklogBoardIcon,
  BacklogIcon,
  BacklogListIcon,
  BackToWindowIcon,
  BadgeIcon,
  BalloonsIcon,
  BankIcon,
  BankSolidIcon,
  BarChart4Icon,
  BarChartHorizontalIcon,
  BarChartVerticalEditIcon,
  BarChartVerticalFillIcon,
  BarChartVerticalFilterIcon,
  BarChartVerticalFilterSolidIcon,
  BarChartVerticalIcon,
  BaseballIcon,
  BeerMugIcon,
  BIDashboardIcon,
  BidiLtrIcon,
  BidiRtlIcon,
  BirthdayCakeIcon,
  BitbucketLogo32Icon,
  BlobStorageIcon,
  BlockContactIcon,
  Blocked12Icon,
  Blocked2Icon,
  Blocked2SolidIcon,
  BlockedIcon,
  BlockedSiteIcon,
  BlockedSiteSolid12Icon,
  BlockedSolidIcon,
  BlogIcon,
  BlowingSnowIcon,
  BlurIcon,
  BoardsIcon,
  BoldIcon,
  BookAnswersIcon,
  BookmarkReportIcon,
  BookmarksIcon,
  BookmarksMirroredIcon,
  BorderDashIcon,
  BorderDotIcon,
  BoxAdditionSolidIcon,
  BoxCheckmarkSolidIcon,
  BoxLogoIcon,
  BoxMultiplySolidIcon,
  BoxPlaySolidIcon,
  BoxSubtractSolidIcon,
  BranchCommitIcon,
  BranchCompareIcon,
  BranchFork2Icon,
  BranchForkIcon,
  BranchLockedIcon,
  BranchMergeIcon,
  BranchPullRequestIcon,
  BranchSearchIcon,
  BranchShelvesetIcon,
  BreadcrumbIcon,
  BreakfastIcon,
  BrightnessIcon,
  BroomIcon,
  BrowserScreenShotIcon,
  BrowserTabIcon,
  BrowserTabScreenshotIcon,
  BrunchIcon,
  BrushIcon,
  BucketColorFillIcon,
  BucketColorIcon,
  BufferTimeAfterIcon,
  BufferTimeBeforeIcon,
  BufferTimeBothIcon,
  BugBlockIcon,
  BugIcon,
  BugSolidIcon,
  BugSyncIcon,
  BuildDefinitionIcon,
  BuildIcon,
  BuildIssueIcon,
  BuildQueueIcon,
  BuildQueueNewIcon,
  BulkUploadIcon,
  BulletedList2Icon,
  BulletedList2MirroredIcon,
  BulletedListBulletIcon,
  BulletedListBulletMirroredIcon,
  BulletedListIcon,
  BulletedListMirroredIcon,
  BulletedListTextIcon,
  BulletedListTextMirroredIcon,
  BulletedTreeListIcon,
  BullseyeIcon,
  BullseyeTargetEditIcon,
  BullseyeTargetIcon,
  BusIcon,
  BusinessHoursSignIcon,
  BusSolidIcon,
  ButtonControlIcon,
  CafeIcon,
  CakeIcon,
  CalculatorAdditionIcon,
  CalculatorDeltaIcon,
  CalculatorEqualToIcon,
  CalculatorGroupIcon,
  CalculatorIcon,
  CalculatorMultiplyIcon,
  CalculatorNotEqualToIcon,
  CalculatorPercentageIcon,
  CalculatorSubtractIcon,
  CalendarAgendaIcon,
  CalendarDayIcon,
  CalendarIcon,
  CalendarMirroredIcon,
  CalendarReplyIcon,
  CalendarSettingsIcon,
  CalendarSettingsMirroredIcon,
  CalendarWeekIcon,
  CalendarWorkWeekIcon,
  CalendarYearIcon,
  CaloriesAddIcon,
  CaloriesIcon,
  CameraIcon,
  CampaignTemplateIcon,
  CancelIcon,
  CannedChatIcon,
  CaretBottomLeftCenter8Icon,
  CaretBottomLeftSolid8Icon,
  CaretBottomRightCenter8Icon,
  CaretBottomRightSolid8Icon,
  CaretDown8Icon,
  CaretDownSolid8Icon,
  CaretHollowIcon,
  CaretHollowMirroredIcon,
  CaretLeft8Icon,
  CaretLeftSolid8Icon,
  CaretRight8Icon,
  CaretRightIcon,
  CaretRightSolid8Icon,
  CaretSolid16Icon,
  CaretSolidDownIcon,
  CaretSolidIcon,
  CaretSolidLeftIcon,
  CaretSolidMirroredIcon,
  CaretSolidRightIcon,
  CaretSolidUpIcon,
  CaretTopLeftCenter8Icon,
  CaretTopLeftSolid8Icon,
  CaretTopRightCenter8Icon,
  CaretTopRightSolid8Icon,
  CaretUp8Icon,
  CaretUpSolid8Icon,
  CarIcon,
  CatIcon,
  CellPhoneIcon,
  CertificateIcon,
  CertifiedDatabaseIcon,
  ChangeEntitlementsIcon,
  ChartIcon,
  ChartSeriesIcon,
  ChartTemplateIcon,
  ChartXAngleIcon,
  ChartYAngleIcon,
  ChatBotIcon,
  ChatIcon,
  ChatInviteFriendIcon,
  ChatSolidIcon,
  CheckboxCompositeIcon,
  CheckboxCompositeReversedIcon,
  CheckboxFillIcon,
  CheckboxIcon,
  CheckboxIndeterminateIcon,
  CheckedOutByOther12Icon,
  CheckedOutByYou12Icon,
  CheckListCheckIcon,
  CheckListCheckMirroredIcon,
  CheckListIcon,
  CheckListTextIcon,
  CheckListTextMirroredIcon,
  CheckMarkIcon,
  ChevronDownEnd6Icon,
  ChevronDownIcon,
  ChevronDownMedIcon,
  ChevronDownSmallIcon,
  ChevronFold10Icon,
  ChevronLeftEnd6Icon,
  ChevronLeftIcon,
  ChevronLeftMedIcon,
  ChevronLeftSmallIcon,
  ChevronRightEnd6Icon,
  ChevronRightIcon,
  ChevronRightMedIcon,
  ChevronRightSmallIcon,
  ChevronUnfold10Icon,
  ChevronUpEnd6Icon,
  ChevronUpIcon,
  ChevronUpMedIcon,
  ChevronUpSmallIcon,
  ChildofIcon,
  ChopsticksIcon,
  ChromeBackIcon,
  ChromeBackMirroredIcon,
  ChromeCloseIcon,
  ChromeFullScreenIcon,
  ChromeMinimizeIcon,
  ChromeRestoreIcon,
  ChronosLogoIcon,
  CircleAdditionIcon,
  CircleAdditionSolidIcon,
  CircleFillIcon,
  CircleHalfFullIcon,
  CirclePauseIcon,
  CirclePauseSolidIcon,
  CirclePlusIcon,
  CircleRingIcon,
  CircleShapeIcon,
  CircleShapeSolidIcon,
  CircleStopIcon,
  CircleStopSolidIcon,
  CityNext2Icon,
  CityNextIcon,
  ClearFilterIcon,
  ClearFormattingAIcon,
  ClearFormattingEraserIcon,
  ClearFormattingIcon,
  ClearIcon,
  ClearNightIcon,
  ClearSelectionIcon,
  ClearSelectionMirroredIcon,
  ClipboardListIcon,
  ClipboardListMirroredIcon,
  ClipboardSolidIcon,
  ClockIcon,
  CloneToDesktopIcon,
  ClosedCaptionIcon,
  ClosePaneIcon,
  ClosePaneMirroredIcon,
  CloudWeatherIcon,
  CloudyIcon,
  CocktailsIcon,
  CodeEditIcon,
  CodeIcon,
  CoffeeIcon,
  CoffeeScriptIcon,
  CollapseContentIcon,
  CollapseContentSingleIcon,
  CollapseMenuIcon,
  CollegeFootballIcon,
  CollegeHoopsIcon,
  ColorIcon,
  ColorSolidIcon,
  ColumnIcon,
  ColumnLeftTwoThirdsEditIcon,
  ColumnLeftTwoThirdsIcon,
  ColumnOptionsIcon,
  ColumnRightTwoThirdsEditIcon,
  ColumnRightTwoThirdsIcon,
  ColumnVerticalSectionEditIcon,
  ColumnVerticalSectionIcon,
  CombineIcon,
  ComboboxIcon,
  CommandPromptIcon,
  CommentActiveIcon,
  CommentAddIcon,
  CommentIcon,
  CommentNextIcon,
  CommentPreviousIcon,
  CommentSolidIcon,
  CommentUrgentIcon,
  CommitmentsIcon,
  CommonDataServiceCDSIcon,
  CommunicationsIcon,
  CompanyDirectoryIcon,
  CompanyDirectoryMirroredIcon,
  CompareIcon,
  CompareUnevenIcon,
  CompassNWIcon,
  CompletedIcon,
  CompletedSolidIcon,
  ComplianceAuditIcon,
  ConfigurationSolidIcon,
  ConnectContactsIcon,
  ConnectVirtualMachineIcon,
  ConstructionConeIcon,
  ConstructionConeSolidIcon,
  ContactCardIcon,
  ContactCardSettingsIcon,
  ContactCardSettingsMirroredIcon,
  ContactHeartIcon,
  ContactIcon,
  ContactInfoIcon,
  ContactLinkIcon,
  ContactListIcon,
  ContactLockIcon,
  ContentFeedIcon,
  ContentSettingsIcon,
  ContextMenuIcon,
  ContrastIcon,
  CopyEditIcon,
  CopyIcon,
  CottonIcon,
  CouponIcon,
  CPlusPlusIcon,
  CPlusPlusLanguageIcon,
  CreateMailRuleIcon,
  CricketIcon,
  CRMProcessesIcon,
  CRMReportIcon,
  CRMServicesIcon,
  CropIcon,
  CrownIcon,
  CrownSolidIcon,
  CSSIcon,
  CubeShapeIcon,
  CubeShapeSolidIcon,
  CurrencyIcon,
  CustomizeToolbarIcon,
  CustomListIcon,
  CustomListMirroredIcon,
  CutIcon,
  CyclingIcon,
  DashboardAddIcon,
  DatabaseIcon,
  DatabaseSyncIcon,
  DatabaseViewIcon,
  DataConnectionLibraryIcon,
  DataflowsIcon,
  DataflowsLinkIcon,
  DataManagementSettingsIcon,
  DateTime12Icon,
  DateTime2Icon,
  DateTimeIcon,
  DateTimeMirroredIcon,
  DeactivateOrdersIcon,
  DecimalsIcon,
  DecisionSolidIcon,
  DeclineCallIcon,
  DecreaseIndentArrowIcon,
  DecreaseIndentArrowMirroredIcon,
  DecreaseIndentIcon,
  DecreaseIndentLegacyIcon,
  DecreaseIndentMirroredIcon,
  DecreaseIndentTextIcon,
  DecreaseIndentTextMirroredIcon,
  DefaultRatioIcon,
  DefectSolidIcon,
  DeleteColumnsIcon,
  DeleteIcon,
  DeleteRowsIcon,
  DeleteRowsMirroredIcon,
  DeleteTableIcon,
  DeliveryTruckIcon,
  DependencyAddIcon,
  DependencyRemoveIcon,
  DeployIcon,
  DescendingIcon,
  DesignIcon,
  DesktopScreenshotIcon,
  DeveloperToolsIcon,
  DeviceBugIcon,
  DeviceOffIcon,
  DeviceRunIcon,
  Devices2Icon,
  Devices3Icon,
  Devices4Icon,
  DiagnosticDataBarTooltipIcon,
  DiagnosticIcon,
  DialpadIcon,
  DiamondIcon,
  DiamondSolidIcon,
  DictionaryIcon,
  DictionaryRemoveIcon,
  DietPlanNotebookIcon,
  DiffInlineIcon,
  DiffSideBySideIcon,
  DisableUpdatesIcon,
  DisconnectVirtualMachineIcon,
  DislikeIcon,
  DislikeSolidIcon,
  DistributeDownIcon,
  DockerLogoIcon,
  DockLeftIcon,
  DockLeftMirroredIcon,
  DockRightIcon,
  DocLibraryIcon,
  DocumentApprovalIcon,
  DocumentationIcon,
  DocumentIcon,
  DocumentManagementIcon,
  DocumentReplyIcon,
  DocumentSearchIcon,
  DocumentSetIcon,
  DOMIcon,
  DonutChartIcon,
  DoorIcon,
  DoubleBookmarkIcon,
  DoubleChevronDown12Icon,
  DoubleChevronDown8Icon,
  DoubleChevronDownIcon,
  DoubleChevronLeft12Icon,
  DoubleChevronLeft8Icon,
  DoubleChevronLeftIcon,
  DoubleChevronLeftMedIcon,
  DoubleChevronLeftMedMirroredIcon,
  DoubleChevronRight12Icon,
  DoubleChevronRight8Icon,
  DoubleChevronRightIcon,
  DoubleChevronUp12Icon,
  DoubleChevronUp8Icon,
  DoubleChevronUpIcon,
  DoubleColumnEditIcon,
  DoubleColumnIcon,
  DoubleDownArrowIcon,
  DownIcon,
  DownloadDocumentIcon,
  DownloadIcon,
  DragObjectIcon,
  DrillDownIcon,
  DrillDownSolidIcon,
  DrillExpandIcon,
  DrillShowIcon,
  DrillThroughIcon,
  DriverOffIcon,
  DRMIcon,
  DropboxLogoIcon,
  DropdownIcon,
  DropIcon,
  DropShapeIcon,
  DropShapeSolidIcon,
  DuplicateRowIcon,
  DuststormIcon,
  EatDrinkIcon,
  EditContactIcon,
  EditCreateIcon,
  EditIcon,
  EditMailIcon,
  EditMirroredIcon,
  EditNoteIcon,
  EditPhotoIcon,
  EditSolid12Icon,
  EditSolidMirrored12Icon,
  EditStyleIcon,
  EducationIcon,
  EgnyteLogoIcon,
  EllipseIcon,
  EmbedIcon,
  EMIIcon,
  Emoji2Icon,
  EmojiDisappointedIcon,
  EmojiIcon,
  EmojiNeutralIcon,
  EmojiTabSymbolsIcon,
  EmptyRecycleBinIcon,
  EncryptionIcon,
  EndPointSolidIcon,
  EngineeringGroupIcon,
  EntitlementPolicyIcon,
  EntitlementRedemptionIcon,
  EntryDeclineIcon,
  EntryViewIcon,
  EqualizerIcon,
  EraseToolIcon,
  ErrorBadgeIcon,
  ErrorIcon,
  Event12Icon,
  EventAcceptedIcon,
  EventDateIcon,
  EventDateMissed12Icon,
  EventDeclinedIcon,
  EventIcon,
  EventInfoIcon,
  EventTentativeIcon,
  EventTentativeMirroredIcon,
  EventToDoLogoIcon,
  ExerciseTrackerIcon,
  ExpandMenuIcon,
  ExploreContentIcon,
  ExploreContentSingleIcon,
  ExploreDataIcon,
  ExportIcon,
  ExportMirroredIcon,
  ExternalBuildIcon,
  ExternalGitIcon,
  ExternalTFVCIcon,
  ExternalXAMLIcon,
  EyedropperIcon,
  EyeShadowIcon,
  F12DevToolsIcon,
  FacebookLogoIcon,
  FamilyIcon,
  FangBodyIcon,
  FastForwardEightXIcon,
  FastForwardFourXIcon,
  FastForwardIcon,
  FastForwardOneFiveXIcon,
  FastForwardOneXIcon,
  FastForwardPointFiveXIcon,
  FastForwardTwoXIcon,
  FastModeIcon,
  FaviconIcon,
  FavoriteListIcon,
  FavoriteStarFillIcon,
  FavoriteStarIcon,
  FaxIcon,
  FeedbackIcon,
  FeedbackRequestMirroredSolidIcon,
  FeedbackRequestSolidIcon,
  FeedbackResponseSolidIcon,
  FerryIcon,
  FerrySolidIcon,
  FieldChangedIcon,
  FieldEmptyIcon,
  FieldFilledIcon,
  FieldNotChangedIcon,
  FieldReadOnlyIcon,
  FieldRequiredIcon,
  FileASPXIcon,
  FileBugIcon,
  FileCodeIcon,
  FileCommentIcon,
  FileCSSIcon,
  FileHTMLIcon,
  FileImageIcon,
  FileJAVAIcon,
  FileLessIcon,
  FileOffIcon,
  FilePDBIcon,
  FileRequestIcon,
  FileSassIcon,
  FileSQLIcon,
  FileSymlinkIcon,
  FileSystemIcon,
  FileTemplateIcon,
  FileYMLIcon,
  FilterAscendingIcon,
  FilterDescendingIcon,
  FilterIcon,
  FilterSettingsIcon,
  FiltersIcon,
  FilterSolidIcon,
  FiltersSolidIcon,
  FinancialIcon,
  FinancialMirroredSolidIcon,
  FinancialSolidIcon,
  FingerprintIcon,
  FitPageIcon,
  FitWidthIcon,
  FiveTileGridIcon,
  FixedAssetManagementIcon,
  FixedColumnWidthIcon,
  FlagIcon,
  FlameSolidIcon,
  FlashAutoIcon,
  FlashlightIcon,
  FlashOffIcon,
  FlickDownIcon,
  FlickLeftIcon,
  FlickRightIcon,
  FlickUpIcon,
  FlowChartIcon,
  FlowerIcon,
  FlowIcon,
  FocalPointIcon,
  FocusIcon,
  FocusViewIcon,
  FogIcon,
  FolderFillIcon,
  FolderHorizontalIcon,
  FolderIcon,
  FolderListIcon,
  FolderListMirroredIcon,
  FolderOpenIcon,
  FolderQueryIcon,
  FolderSearchIcon,
  FollowUserIcon,
  FontColorAIcon,
  FontColorIcon,
  FontColorSwatchIcon,
  FontDecreaseIcon,
  FontIcon,
  FontIncreaseIcon,
  FontSize2Icon,
  FontSizeIcon,
  FooterIcon,
  FormatPainterIcon,
  FormLibraryIcon,
  FormLibraryMirroredIcon,
  ForumIcon,
  ForwardEventIcon,
  ForwardIcon,
  FreezingIcon,
  FrigidIcon,
  FrontCameraIcon,
  FullCircleMaskIcon,
  FullHistoryIcon,
  FullScreenIcon,
  FullViewIcon,
  FullWidthEditIcon,
  FullWidthIcon,
  FunctionalManagerDashboardIcon,
  FunnelChartIcon,
  GameIcon,
  GatherIcon,
  GenerateIcon,
  GenericScanFilledIcon,
  GenericScanIcon,
  GIFIcon,
  GiftboxIcon,
  GiftboxOpenIcon,
  GiftBoxSolidIcon,
  GiftCardIcon,
  GitForkIcon,
  GitGraphIcon,
  GitHubLogoIcon,
  GitLogoIcon,
  GlassesIcon,
  GlimmerIcon,
  GlobalNavButtonActiveIcon,
  GlobalNavButtonIcon,
  Globe2Icon,
  GlobeFavoriteIcon,
  GlobeIcon,
  GoIcon,
  GolfIcon,
  GoMirroredIcon,
  GoogleDriveLogoBottomBlueIcon,
  GoogleDriveLogoIcon,
  GoogleDriveLogoLeftGreenIcon,
  GoogleDriveLogoRightYellowIcon,
  GoToDashboardIcon,
  GotoTodayIcon,
  GradleLogo32Icon,
  GreetingCardIcon,
  GridViewLargeIcon,
  GridViewMediumIcon,
  GridViewSmallIcon,
  GripperBarHorizontalIcon,
  GripperBarVerticalIcon,
  GripperDotsVerticalIcon,
  GripperToolIcon,
  GroupedAscendingIcon,
  GroupedDescendingIcon,
  GroupedListIcon,
  GroupIcon,
  GroupListIcon,
  GroupObjectIcon,
  GUIDIcon,
  GuitarIcon,
  HailDayIcon,
  HailNightIcon,
  HalfAlphaIcon,
  HalfCircleIcon,
  HandsFreeIcon,
  HandwritingIcon,
  HardDriveGroupIcon,
  HardDriveIcon,
  HardDriveLockIcon,
  HardDriveUnlockIcon,
  Header1Icon,
  Header2Icon,
  Header3Icon,
  Header4Icon,
  HeaderIcon,
  HeadsetIcon,
  HeadsetSolidIcon,
  HealthIcon,
  HealthRefreshIcon,
  HealthSolidIcon,
  HeartBrokenIcon,
  HeartFillIcon,
  HeartIcon,
  HelpIcon,
  HelpMirroredIcon,
  HexaditeInvestigationCancelIcon,
  HexaditeInvestigationIcon,
  HexaditeInvestigationSemiAutoIcon,
  HexagonIcon,
  Hide2Icon,
  Hide3Icon,
  HideIcon,
  HighlightIcon,
  HighlightMappedShapesIcon,
  HintTextIcon,
  HistoricalWeatherIcon,
  HistoryIcon,
  HomeDropdownIcon,
  HomeGroupIcon,
  HomeIcon,
  HomeSolidIcon,
  HomeVerifyIcon,
  HorizontalDistributeCenterIcon,
  HorizontalTabKeyIcon,
  HospitalIcon,
  HotelIcon,
  HourGlassIcon,
  IconSetsFlagIcon,
  IDBadgeIcon,
  IgnoreConversationIcon,
  ImageCrosshairIcon,
  ImageDiffIcon,
  ImageInARIcon,
  ImagePixelIcon,
  ImageSearchIcon,
  ImportAllMirroredIcon,
  ImportantIcon,
  ImportIcon,
  ImportMirroredIcon,
  InboxCheckIcon,
  InboxIcon,
  IncidentTriangleIcon,
  IncomingCallIcon,
  IncreaseIndentArrowIcon,
  IncreaseIndentArrowMirroredIcon,
  IncreaseIndentHangingIcon,
  IncreaseIndentHangingMirroredIcon,
  IncreaseIndentIcon,
  IncreaseIndentLegacyIcon,
  IncreaseIndentMirroredIcon,
  IncreaseIndentTextIcon,
  IncreaseIndentTextMirroredIcon,
  IndentFirstLineIcon,
  Info2Icon,
  InfoIcon,
  InformationBarriersIcon,
  InfoSolidIcon,
  InkingToolIcon,
  InputAddressIcon,
  InsertColumnsLeftIcon,
  InsertColumnsRightIcon,
  InsertIcon,
  InsertRowsAboveIcon,
  InsertRowsBelowIcon,
  InsertSignatureLineIcon,
  InsertTextBoxIcon,
  InsightsIcon,
  InstallationIcon,
  InstallToDriveIcon,
  InternalInvestigationIcon,
  InternetSharingIcon,
  IOTIcon,
  IRMForwardIcon,
  IRMForwardMirroredIcon,
  IRMReplyIcon,
  IRMReplyMirroredIcon,
  IssueSolidIcon,
  IssueTrackingIcon,
  IssueTrackingMirroredIcon,
  ItalicIcon,
  JavaLogoIcon,
  JavaScriptLanguageIcon,
  JenkinsLogoIcon,
  JoinOnlineMeetingIcon,
  JSIcon,
  KeubernetesLogoIcon,
  KeyboardClassicIcon,
  KeyPhraseExtractionIcon,
  KnowledgeArticleIcon,
  LabelIcon,
  LadybugSolidIcon,
  LampIcon,
  LandscapeOrientationIcon,
  LaptopSecureIcon,
  LaptopSelectedIcon,
  LargeGridIcon,
  LearningToolsIcon,
  LeaveIcon,
  LeaveUserIcon,
  LibraryIcon,
  LifesaverIcon,
  LifesaverLockIcon,
  LightbulbIcon,
  LightIcon,
  LightningBoltIcon,
  LightningBoltSolidIcon,
  LightWeightIcon,
  LikeIcon,
  LikeSolidIcon,
  LineChartIcon,
  LineIcon,
  LineSpacingIcon,
  LineStyleIcon,
  LineThicknessIcon,
  Link12Icon,
  LinkedDatabaseIcon,
  LinkIcon,
  LinuxLogo32Icon,
  ListIcon,
  ListMirroredIcon,
  LiveSiteIcon,
  LocaleLanguageIcon,
  LocationCircleIcon,
  LocationDotIcon,
  LocationFillIcon,
  LocationIcon,
  LocationOutlineIcon,
  Lock12Icon,
  LockIcon,
  LockShareIcon,
  LockSolidIcon,
  LogRemoveIcon,
  LookupEntitiesIcon,
  LowerBrightnessIcon,
  MachineLearningIcon,
  MailAlertIcon,
  MailAttachedIcon,
  MailCheckIcon,
  MailFillIcon,
  MailForwardIcon,
  MailForwardMirroredIcon,
  MailIcon,
  MailLowImportanceIcon,
  MailOptionsIcon,
  MailPauseIcon,
  MailReminderIcon,
  MailRepeatIcon,
  MailReplyAllIcon,
  MailReplyAllMirroredIcon,
  MailReplyIcon,
  MailReplyMirroredIcon,
  MailScheduleIcon,
  MailSolidIcon,
  MailTentativeIcon,
  MailTentativeMirroredIcon,
  MailUndeliveredIcon,
  ManagerSelfServiceIcon,
  ManufacturingIcon,
  MapDirectionsIcon,
  MapLayersIcon,
  MapPin12Icon,
  MapPinIcon,
  MapPinSolidIcon,
  MarkAsProtectedIcon,
  MarkDownLanguageIcon,
  MarketDownIcon,
  MarketIcon,
  MasterDatabaseIcon,
  MaximumValueIcon,
  MedalIcon,
  MedalSolidIcon,
  MediaAddIcon,
  MediaIcon,
  MedicalIcon,
  MegaphoneIcon,
  MegaphoneSolidIcon,
  MemoIcon,
  MergeDuplicateIcon,
  MergeIcon,
  MessageFillIcon,
  MessageFriendRequestIcon,
  MessageIcon,
  MicOff2Icon,
  MicOffIcon,
  MicrophoneIcon,
  MiniContractIcon,
  MiniContractMirroredIcon,
  MiniExpandIcon,
  MiniExpandMirroredIcon,
  MiniLinkIcon,
  MinimumValueIcon,
  MiracastLogoLargeIcon,
  MobileAngledIcon,
  MobileReportIcon,
  MobileSelectedIcon,
  ModelingViewIcon,
  MoneyIcon,
  MoreIcon,
  MoreSportsIcon,
  MoreVerticalIcon,
  MountainClimbingIcon,
  MoveIcon,
  MoversIcon,
  MoveToFolderIcon,
  MultiSelectIcon,
  MultiSelectMirroredIcon,
  MusicInCollectionFillIcon,
  MusicInCollectionIcon,
  MusicNoteIcon,
  MuteChatIcon,
  MyMoviesTVIcon,
  MyNetworkIcon,
  Nav2DMapViewIcon,
  NavigateBackIcon,
  NavigateBackMirroredIcon,
  NavigateExternalInlineIcon,
  NavigateForwardIcon,
  NavigateForwardMirroredIcon,
  NavigationFlipperIcon,
  NetworkTowerIcon,
  NewAnalyticsQueryIcon,
  NewFolderIcon,
  NewMailIcon,
  NewsIcon,
  NewsSearchIcon,
  NewTeamProjectIcon,
  NextIcon,
  NonprofitLogo32Icon,
  NormalWeightIcon,
  NoteForwardIcon,
  NotePinnedIcon,
  NoteReplyIcon,
  NotExecutedIcon,
  NotImpactedSolidIcon,
  NPMLogoIcon,
  NumberedListIcon,
  NumberedListMirroredIcon,
  NumberedListNumberIcon,
  NumberedListNumberMirroredIcon,
  NumberedListTextIcon,
  NumberedListTextMirroredIcon,
  NumberFieldIcon,
  NumberIcon,
  NumberSequenceIcon,
  NumberSymbolIcon,
  OctagonIcon,
  OEMIcon,
  OfficeChatIcon,
  OfficeChatSolidIcon,
  OfflineStorageIcon,
  OfflineStorageSolidIcon,
  OnboardingIcon,
  OpenEnrollmentIcon,
  OpenFileIcon,
  OpenFolderHorizontalIcon,
  OpenInNewTabIcon,
  OpenInNewWindowIcon,
  OpenPaneIcon,
  OpenPaneMirroredIcon,
  OpenSourceIcon,
  OpenWithIcon,
  OpenWithMirroredIcon,
  OrgIcon,
  Orientation2Icon,
  OrientationIcon,
  OutOfOfficeIcon,
  PackageIcon,
  PackagesIcon,
  PaddingBottomIcon,
  PaddingIcon,
  PaddingLeftIcon,
  PaddingRightIcon,
  PaddingTopIcon,
  PageAddIcon,
  PageArrowRightIcon,
  PageCheckedinIcon,
  PageCheckedOutIcon,
  PageDataIcon,
  PageEditIcon,
  PageHeaderEditIcon,
  PageHeaderIcon,
  PageIcon,
  PageLeftIcon,
  PageLinkIcon,
  PageListFilterIcon,
  PageListIcon,
  PageListMirroredSolidIcon,
  PageListSolidIcon,
  PageLockIcon,
  PageRemoveIcon,
  PageRightIcon,
  PageSharedIcon,
  PageSolidIcon,
  PanoIndicatorIcon,
  ParachuteIcon,
  ParachuteSolidIcon,
  ParameterIcon,
  ParatureLogoIcon,
  ParkingLocationIcon,
  ParkingLocationMirroredIcon,
  ParkingMirroredSolidIcon,
  ParkingSolidIcon,
  PartlyCloudyDayIcon,
  PartlyCloudyNightIcon,
  PartyLeaderIcon,
  PassiveAuthenticationIcon,
  PasswordFieldIcon,
  PasteAsCodeIcon,
  PasteAsTextIcon,
  PasteIcon,
  PauseIcon,
  PaymentCardIcon,
  PC1Icon,
  PDFIcon,
  PencilReplyIcon,
  PentagonIcon,
  PenWorkspaceIcon,
  PeopleAddIcon,
  PeopleAlertIcon,
  PeopleBlockIcon,
  PeopleIcon,
  PeoplePauseIcon,
  PeopleRepeatIcon,
  PermissionsIcon,
  PermissionsSolidIcon,
  PersonalizeIcon,
  PhishingIcon,
  PhoneIcon,
  Photo2AddIcon,
  Photo2FillIcon,
  Photo2Icon,
  Photo2RemoveIcon,
  PhotoCollectionIcon,
  PhotoErrorIcon,
  PhotoIcon,
  PhotoVideoMediaIcon,
  PictureCenterIcon,
  PictureFillIcon,
  PictureIcon,
  PictureLibraryIcon,
  PicturePositionIcon,
  PictureStretchIcon,
  PictureTileIcon,
  PieDoubleIcon,
  PieSingleIcon,
  PieSingleSolidIcon,
  PillIcon,
  PinIcon,
  PinnedFillIcon,
  PinnedIcon,
  PinnedSolidIcon,
  PinSolid12Icon,
  PinSolidOff12Icon,
  PivotChartIcon,
  PlainTextIcon,
  PlanViewIcon,
  PlaybackRate1xIcon,
  PlayerSettingsIcon,
  PlayIcon,
  PlayResumeIcon,
  PlayReverseIcon,
  PlayReverseResumeIcon,
  PlaySolidIcon,
  PlugConnectedIcon,
  PlugDisconnectedIcon,
  PlugIcon,
  PlugSolidIcon,
  POIIcon,
  POISolidIcon,
  PollResultsIcon,
  PostUpdateIcon,
  PowerButtonIcon,
  PrecipitationIcon,
  PresenceChickletVideoIcon,
  Presentation12Icon,
  PresentationIcon,
  PreviewIcon,
  PreviewLinkIcon,
  PreviousIcon,
  PrimaryCalendarIcon,
  PrintfaxPrinterFileIcon,
  PrintIcon,
  ProcessingCancelIcon,
  ProcessingIcon,
  ProcessingPauseIcon,
  ProcessingRunIcon,
  ProcessMetaTaskIcon,
  ProductCatalogIcon,
  ProductIcon,
  ProductionFloorManagementIcon,
  ProductListIcon,
  ProductReleaseIcon,
  ProductVariantIcon,
  ProfileSearchIcon,
  ProFootballIcon,
  ProgressLoopInnerIcon,
  ProgressLoopOuterIcon,
  ProgressRingDotsIcon,
  ProHockeyIcon,
  PromotedDatabaseIcon,
  ProtectedDocumentIcon,
  ProtectRestrictIcon,
  ProvisioningPackageIcon,
  PublicCalendarIcon,
  PublicContactCardIcon,
  PublicContactCardMirroredIcon,
  PublicEmailIcon,
  PublicFolderIcon,
  PublishContentIcon,
  PublishCourseIcon,
  PuzzleIcon,
  PYIcon,
  PythonLanguageIcon,
  PythonLogoBlueIcon,
  PythonLogoYellowIcon,
  QandAIcon,
  QandAMirrorIcon,
  QRCodeIcon,
  QuadColumnIcon,
  QuantityIcon,
  QuarterCircleIcon,
  QueryListIcon,
  QuestionnaireIcon,
  QuestionnaireMirroredIcon,
  QuickNoteIcon,
  QuickNoteSolidIcon,
  RadioBtnOffIcon,
  RadioBtnOnIcon,
  RadioBulletIcon,
  RainIcon,
  RainShowersDayIcon,
  RainShowersNightIcon,
  RainSnowIcon,
  RawSourceIcon,
  ReactLogoIcon,
  ReadIcon,
  ReadingModeIcon,
  ReadingModeSolidIcon,
  ReadOutLoudIcon,
  RealEstateIcon,
  ReceiptCheckIcon,
  ReceiptForwardIcon,
  ReceiptReplyIcon,
  ReceiptTentativeIcon,
  ReceiptTentativeMirroredIcon,
  ReceiptUndeliveredIcon,
  RecentIcon,
  Record2Icon,
  RecruitmentManagementIcon,
  RectangleShapeIcon,
  RectangleShapeSolidIcon,
  RectangularClippingIcon,
  RecurringEventIcon,
  RecurringTaskIcon,
  RedeployIcon,
  RedEye12Icon,
  RedEyeIcon,
  RedoIcon,
  RefreshIcon,
  RegistryEditorIcon,
  RelationshipIcon,
  ReleaseDefinitionIcon,
  ReleaseGateCheckIcon,
  ReleaseGateErrorIcon,
  ReleaseGateIcon,
  ReminderGroupIcon,
  ReminderPersonIcon,
  ReminderTimeIcon,
  RemoteIcon,
  RemoveContentIcon,
  RemoveEventIcon,
  RemoveFilterIcon,
  RemoveFromShoppingListIcon,
  RemoveFromTrashIcon,
  RemoveIcon,
  RemoveLinkChainIcon,
  RemoveLinkIcon,
  RemoveLinkXIcon,
  RemoveOccurrenceIcon,
  RenameIcon,
  RenewalCurrentIcon,
  RenewalFutureIcon,
  ReopenPagesIcon,
  RepairIcon,
  RepeatAllIcon,
  RepeatHeaderRowsIcon,
  RepeatOneIcon,
  ReplyAllAltIcon,
  ReplyAllIcon,
  ReplyAllMirroredIcon,
  ReplyAltIcon,
  ReplyIcon,
  ReplyMirroredIcon,
  RepoIcon,
  ReportAddIcon,
  ReportDocumentIcon,
  ReportHackedIcon,
  ReportLibraryIcon,
  ReportLibraryMirroredIcon,
  ReportLockIcon,
  ReportWarningIcon,
  RepoSolidIcon,
  RerunIcon,
  ReservationOrdersIcon,
  ResetDeviceIcon,
  ResetIcon,
  ResponsesMenuIcon,
  ReturnKeyIcon,
  ReturnToSessionIcon,
  ReviewRequestMirroredSolidIcon,
  ReviewRequestSolidIcon,
  ReviewResponseSolidIcon,
  ReviewSolidIcon,
  RevToggleKeyIcon,
  RewindEightXIcon,
  RewindFourXIcon,
  RewindIcon,
  RewindOneFiveXIcon,
  RewindOneXIcon,
  RewindPointFiveXIcon,
  RewindTwoXIcon,
  RibbonIcon,
  RibbonSolidIcon,
  RightDoubleQuoteIcon,
  RightTriangleIcon,
  RingerIcon,
  RingerOffIcon,
  RingerRemoveIcon,
  RingerSolidIcon,
  RobotIcon,
  RocketIcon,
  RoomIcon,
  Rotate90ClockwiseIcon,
  Rotate90CounterClockwiseIcon,
  RotateIcon,
  RowsChildIcon,
  RowsGroupIcon,
  RubyGemsLogoIcon,
  RugbyIcon,
  RunningIcon,
  RustLanguageLogoIcon,
  SadIcon,
  SadSolidIcon,
  SaveAllIcon,
  SaveAndCloseIcon,
  SaveAsIcon,
  SaveIcon,
  SaveTemplateIcon,
  SaveToMobileIcon,
  SavingsIcon,
  ScaleUpIcon,
  ScaleVolumeIcon,
  ScatterChartIcon,
  ScheduleEventActionIcon,
  ScopeTemplateIcon,
  ScreenCastIcon,
  ScreenTimeIcon,
  ScriptIcon,
  ScrollUpDownIcon,
  SDCardIcon,
  SearchAndAppsIcon,
  SearchBookmarkIcon,
  SearchCalendarIcon,
  SearchDataIcon,
  SearchIcon,
  SearchIssueIcon,
  SearchIssueMirroredIcon,
  SearchNearbyIcon,
  SecondaryNavIcon,
  SectionIcon,
  SectionsIcon,
  SecurityGroupIcon,
  SeeDoIcon,
  SelectAllIcon,
  SellIcon,
  SemiboldWeightIcon,
  SendIcon,
  SendMirroredIcon,
  SentimentAnalysisIcon,
  SeparatorIcon,
  ServerEnviromentIcon,
  ServerIcon,
  ServerProcessesIcon,
  ServiceOffIcon,
  SetActionIcon,
  SettingsIcon,
  ShakeDeviceIcon,
  ShapesIcon,
  ShapeSolidIcon,
  SharedDatabaseIcon,
  ShareIcon,
  ShareiOSIcon,
  ShirtIcon,
  ShopIcon,
  ShoppingCartIcon,
  ShoppingCartSolidIcon,
  ShopServerIcon,
  ShowGridIcon,
  ShowResultsIcon,
  ShowResultsMirroredIcon,
  ShowTimeAsIcon,
  SidePanelIcon,
  SidePanelMirroredIcon,
  SigninIcon,
  SignOutIcon,
  SingleBookmarkIcon,
  SingleBookmarkSolidIcon,
  SingleColumnEditIcon,
  SingleColumnIcon,
  SIPMoveIcon,
  SiteScanIcon,
  SixPointStarIcon,
  SizeLegacyIcon,
  SkipBack10Icon,
  SkipForward30Icon,
  SkiResortsIcon,
  SkypeArrowIcon,
  SkypeCheckIcon,
  SkypeClockIcon,
  SkypeMinusIcon,
  SliderHandleSizeIcon,
  SliderIcon,
  SliderThumbIcon,
  SlideshowIcon,
  SmartGlassRemoteIcon,
  SnapToGridIcon,
  SnoozeIcon,
  SnowflakeIcon,
  SnowIcon,
  SnowShowerDayIcon,
  SnowShowerNightIcon,
  SoccerIcon,
  SortDownIcon,
  SortIcon,
  SortLinesAscendingIcon,
  SortLinesIcon,
  SortUpIcon,
  SourceIcon,
  SpacerIcon,
  SpeakersIcon,
  SpecialEventIcon,
  SpeedHighIcon,
  SpellingIcon,
  SplitIcon,
  SplitObjectIcon,
  SprintIcon,
  SQLAnalyticsPoolIcon,
  SquallsIcon,
  SquareShapeIcon,
  SquareShapeSolidIcon,
  StackColumnChartIcon,
  StackedBarChartIcon,
  StackedColumnChart2FillIcon,
  StackedColumnChart2Icon,
  StackedLineChartIcon,
  StackIcon,
  StackIndicatorIcon,
  StarburstIcon,
  StarburstSolidIcon,
  StatusCircleBlock2Icon,
  StatusCircleBlockIcon,
  StatusCircleCheckmarkIcon,
  StatusCircleErrorXIcon,
  StatusCircleExclamationIcon,
  StatusCircleInfoIcon,
  StatusCircleInnerIcon,
  StatusCircleOuterIcon,
  StatusCircleQuestionMarkIcon,
  StatusCircleRingIcon,
  StatusCircleSyncIcon,
  StatusErrorFullIcon,
  StatusTriangleExclamationIcon,
  StatusTriangleIcon,
  StatusTriangleInnerIcon,
  StatusTriangleOuterIcon,
  StepIcon,
  StepInsertIcon,
  StepSharedAddIcon,
  StepSharedIcon,
  StepSharedInsertIcon,
  StockDownIcon,
  StockUpIcon,
  StopIcon,
  StopSolidIcon,
  StopwatchIcon,
  StorageAcountIcon,
  StorageOpticalIcon,
  StoryboardIcon,
  StreamingIcon,
  StreamingOffIcon,
  StreetIcon,
  StreetsideSplitMinimizeIcon,
  StrikethroughIcon,
  SubscribeIcon,
  SubscriptIcon,
  SubstitutionsInIcon,
  SuitcaseIcon,
  SunAddIcon,
  SunnyIcon,
  SunQuestionMarkIcon,
  SuperscriptIcon,
  SurveyQuestionsIcon,
  SVNLogoIcon,
  SwiftLogoIcon,
  SwitcherStartEndIcon,
  SwitchIcon,
  SwitchUserIcon,
  SyncFolderIcon,
  SyncIcon,
  SyncOccurenceIcon,
  SyncStatusIcon,
  SyncStatusSolidIcon,
  SyncToPCIcon,
  SystemIcon,
  TabCenterIcon,
  TabIcon,
  TableBrandedColumnIcon,
  TableBrandedRowIcon,
  TableComputedIcon,
  TableFirstColumnIcon,
  TableGroupIcon,
  TableHeaderRowIcon,
  TableIcon,
  TableLastColumnIcon,
  TableLinkIcon,
  TabletIcon,
  TabletModeIcon,
  TableTotalRowIcon,
  TabletSelectedIcon,
  TabOneColumnIcon,
  TabThreeColumnIcon,
  TabTwoColumnIcon,
  TagGroupIcon,
  TagIcon,
  TagSolidIcon,
  TagUnknown12Icon,
  TagUnknown12MirrorIcon,
  TagUnknownIcon,
  TagUnknownMirrorIcon,
  TaskboardIcon,
  TaskGroupIcon,
  TaskGroupMirroredIcon,
  TaskListIcon,
  TaskManagerIcon,
  TaskManagerMirroredIcon,
  TaskSolidIcon,
  TaxiIcon,
  TeamFavoriteIcon,
  TeamworkIcon,
  TeethIcon,
  TelemarketerIcon,
  TemporaryUserIcon,
  TennisIcon,
  TestAutoSolidIcon,
  TestBeakerIcon,
  TestBeakerSolidIcon,
  TestCaseIcon,
  TestExploreSolidIcon,
  TestImpactSolidIcon,
  TestParameterIcon,
  TestPlanIcon,
  TestStepIcon,
  TestSuiteIcon,
  TestUserSolidIcon,
  TextAlignBottomIcon,
  TextAlignMiddleIcon,
  TextAlignTopIcon,
  TextBoxIcon,
  TextCalloutIcon,
  TextDocumentEditIcon,
  TextDocumentIcon,
  TextDocumentSettingsIcon,
  TextDocumentSharedIcon,
  TextFieldIcon,
  TextOverflowIcon,
  TextParagraphOptionIcon,
  TextRecognitionIcon,
  TextRotate270DegreesIcon,
  TextRotate90DegreesIcon,
  TextRotateHorizontalIcon,
  TextRotationIcon,
  ThisPCIcon,
  ThreeQuarterCircleIcon,
  ThumbnailViewIcon,
  ThumbnailViewMirroredIcon,
  ThunderstormsIcon,
  TicketIcon,
  Tiles2Icon,
  TilesIcon,
  TimeEntryIcon,
  TimelineDeliveryIcon,
  TimelineIcon,
  TimelineMatrixViewIcon,
  TimelineProgressIcon,
  TimePickerIcon,
  TimerIcon,
  TimeSheetIcon,
  ToggleBorderIcon,
  ToggleFilledIcon,
  ToggleLeftIcon,
  ToggleRightIcon,
  ToggleThumbIcon,
  TollIcon,
  ToolboxIcon,
  TotalIcon,
  TouchIcon,
  TouchPointerIcon,
  TrackersIcon,
  TrackersMirroredIcon,
  TrainIcon,
  TrainSolidIcon,
  TransferCallIcon,
  TransitionEffectIcon,
  TransitionIcon,
  TransitionPopIcon,
  TransitionPushIcon,
  TranslateIcon,
  Trending12Icon,
  TriangleDown12Icon,
  TriangleLeft12Icon,
  TriangleRight12Icon,
  TriangleShapeIcon,
  TriangleShapeSolidIcon,
  TriangleSolidDown12Icon,
  TriangleSolidIcon,
  TriangleSolidLeft12Icon,
  TriangleSolidRight12Icon,
  TriangleSolidUp12Icon,
  TriangleUp12Icon,
  TriggerApprovalIcon,
  TriggerAutoIcon,
  TriggerUserIcon,
  TrimEndIcon,
  TrimIcon,
  TrimStartIcon,
  TripleColumnEditIcon,
  TripleColumnIcon,
  TripleColumnWideIcon,
  Trophy2Icon,
  Trophy2SolidIcon,
  TrophyIcon,
  TurnRightIcon,
  TVMonitorIcon,
  TVMonitorSelectedIcon,
  TwelvePointStarIcon,
  TwitterLogoIcon,
  UmbrellaIcon,
  UnderlineIcon,
  UndoIcon,
  Uneditable2Icon,
  Uneditable2MirroredIcon,
  UneditableIcon,
  UneditableMirroredIcon,
  UneditableSolid12Icon,
  UneditableSolidMirrored12Icon,
  UnfavoriteIcon,
  UngroupObjectIcon,
  UnknownCallIcon,
  UnknownIcon,
  UnknownMirroredIcon,
  UnknownMirroredSolidIcon,
  UnknownSolidIcon,
  UnlockIcon,
  UnlockSolidIcon,
  UnpinIcon,
  UnpublishContentIcon,
  UnSetColorIcon,
  UnstackSelectedIcon,
  UnsubscribeIcon,
  UnsyncFolderIcon,
  UnsyncOccurenceIcon,
  UntagIcon,
  UpdateRestoreIcon,
  UpgradeAnalysisIcon,
  UpIcon,
  UploadIcon,
  URLBlockIcon,
  USBIcon,
  UserEventIcon,
  UserFollowedIcon,
  UserGaugeIcon,
  UserOptionalIcon,
  UserPauseIcon,
  UserRemoveIcon,
  UserSyncIcon,
  UserWarningIcon,
  VacationIcon,
  VaccinationIcon,
  Variable2Icon,
  VariableGroupIcon,
  VariableIcon,
  VBIcon,
  VennDiagramIcon,
  VerifiedBrandIcon,
  VerifiedBrandSolidIcon,
  VersionControlPushIcon,
  VerticalDistributeCenterIcon,
  Video360GenericIcon,
  VideoIcon,
  VideoLightOffIcon,
  VideoOff2Icon,
  VideoOffIcon,
  VideoSearchIcon,
  VideoSolidIcon,
  ViewAll2Icon,
  ViewAllIcon,
  ViewDashboardIcon,
  ViewIcon,
  ViewInARIcon,
  ViewListGroupIcon,
  ViewListIcon,
  ViewListTreeIcon,
  ViewOriginalIcon,
  VisuallyImpairedIcon,
  VisualsFolderIcon,
  VisualsStoreIcon,
  VoicemailForwardIcon,
  VoicemailIRMIcon,
  VoicemailReplyIcon,
  Volume0Icon,
  Volume1Icon,
  Volume2Icon,
  Volume3Icon,
  VolumeDisabledIcon,
  WaffleIcon,
  WaitlistConfirmIcon,
  WaitlistConfirmMirroredIcon,
  Warning12Icon,
  WarningIcon,
  WarningSolidIcon,
  WavingHandIcon,
  Webcam2Icon,
  Webcam2OffIcon,
  WebComponentsIcon,
  WebEnvironmentIcon,
  WebPublishIcon,
  WebsiteIcon,
  WebTemplateIcon,
  WeightsIcon,
  WheelchairIcon,
  WifiEthernetIcon,
  WifiWarning4Icon,
  WindDirectionIcon,
  WindowEditIcon,
  WinesIcon,
  WipePhoneIcon,
  WorkFlowIcon,
  WorkforceManagementIcon,
  WorkIcon,
  WorkItemAlertIcon,
  WorkItemBarIcon,
  WorkItemBarSolidIcon,
  WorkItemBugIcon,
  WorkItemIcon,
  WorldClockIcon,
  WorldIcon,
  XamarinLogoIcon,
  XboxControllerIcon,
  ZipFolderIcon,
  ZoomIcon,
  ZoomInIcon,
  ZoomOutIcon,
  ZoomToFitIcon,
} from '@fluentui/react-icons-mdl2'

export const icons = {
  Accept: <AcceptIcon />,
  AcceptMedium: <AcceptMediumIcon />,
  AccessibiltyChecker: <AccessibiltyCheckerIcon />,
  AccessLogo: <AccessLogoIcon />,
  AccountActivity: <AccountActivityIcon />,
  AccountBrowser: <AccountBrowserIcon />,
  AccountManagement: <AccountManagementIcon />,
  Accounts: <AccountsIcon />,
  ActionCenter: <ActionCenterIcon />,
  ActivateOrders: <ActivateOrdersIcon />,
  ActivityFeed: <ActivityFeedIcon />,
  AddBookmark: <AddBookmarkIcon />,
  AddEvent: <AddEventIcon />,
  AddFavoriteFill: <AddFavoriteFillIcon />,
  AddFavorite: <AddFavoriteIcon />,
  AddFriend: <AddFriendIcon />,
  AddGroup: <AddGroupIcon />,
  AddHome: <AddHomeIcon />,
  Add: <AddIcon />,
  AddIn: <AddInIcon />,
  AddLink: <AddLinkIcon />,
  AddNotes: <AddNotesIcon />,
  AddOnlineMeeting: <AddOnlineMeetingIcon />,
  AddPhone: <AddPhoneIcon />,
  AddReaction: <AddReactionIcon />,
  AddSpaceAfter: <AddSpaceAfterIcon />,
  AddSpaceBefore: <AddSpaceBeforeIcon />,
  AddTo: <AddToIcon />,
  AddToShoppingList: <AddToShoppingListIcon />,
  AddWork: <AddWorkIcon />,
  Airplane: <AirplaneIcon />,
  AirplaneSolid: <AirplaneSolidIcon />,
  AirTickets: <AirTicketsIcon />,
  AlarmClock: <AlarmClockIcon />,
  Album: <AlbumIcon />,
  AlbumRemove: <AlbumRemoveIcon />,
  AlertSettings: <AlertSettingsIcon />,
  AlertSolid: <AlertSolidIcon />,
  AlignCenter: <AlignCenterIcon />,
  AlignHorizontalCenter: <AlignHorizontalCenterIcon />,
  AlignHorizontalLeft: <AlignHorizontalLeftIcon />,
  AlignHorizontalRight: <AlignHorizontalRightIcon />,
  AlignJustify: <AlignJustifyIcon />,
  AlignLeft: <AlignLeftIcon />,
  AlignRight: <AlignRightIcon />,
  AlignVerticalBottom: <AlignVerticalBottomIcon />,
  AlignVerticalCenter: <AlignVerticalCenterIcon />,
  AlignVerticalTop: <AlignVerticalTopIcon />,
  AllApps: <AllAppsIcon />,
  AllAppsMirrored: <AllAppsMirroredIcon />,
  AllCurrency: <AllCurrencyIcon />,
  AltText: <AltTextIcon />,
  AmazonWebServicesLogo: <AmazonWebServicesLogoIcon />,
  AnalyticsQuery: <AnalyticsQueryIcon />,
  AnalyticsReport: <AnalyticsReportIcon />,
  AnalyticsView: <AnalyticsViewIcon />,
  AnchorLock: <AnchorLockIcon />,
  AndroidLogo: <AndroidLogoIcon />,
  Annotation: <AnnotationIcon />,
  ApacheIvyLogo32: <ApacheIvyLogo32Icon />,
  ApacheMavenLogo: <ApacheMavenLogoIcon />,
  Archive: <ArchiveIcon />,
  ArchiveUndo: <ArchiveUndoIcon />,
  AreaChart: <AreaChartIcon />,
  ArrangeBringForward: <ArrangeBringForwardIcon />,
  ArrangeBringToFront: <ArrangeBringToFrontIcon />,
  ArrangeByFrom: <ArrangeByFromIcon />,
  ArrangeSendBackward: <ArrangeSendBackwardIcon />,
  ArrangeSendToBack: <ArrangeSendToBackIcon />,
  Arrivals: <ArrivalsIcon />,
  ArrowDownRight8: <ArrowDownRight8Icon />,
  ArrowDownRightMirrored8: <ArrowDownRightMirrored8Icon />,
  ArrowTallDownLeft: <ArrowTallDownLeftIcon />,
  ArrowTallDownRight: <ArrowTallDownRightIcon />,
  ArrowTallUpLeft: <ArrowTallUpLeftIcon />,
  ArrowTallUpRight: <ArrowTallUpRightIcon />,
  ArrowUpRight8: <ArrowUpRight8Icon />,
  ArrowUpRight: <ArrowUpRightIcon />,
  ArrowUpRightMirrored8: <ArrowUpRightMirrored8Icon />,
  Articles: <ArticlesIcon />,
  Ascending: <AscendingIcon />,
  AspectRatio: <AspectRatioIcon />,
  AssessmentGroup: <AssessmentGroupIcon />,
  AssessmentGroupTemplate: <AssessmentGroupTemplateIcon />,
  AssetLibrary: <AssetLibraryIcon />,
  Assign: <AssignIcon />,
  AssignPolicy: <AssignPolicyIcon />,
  Asterisk: <AsteriskIcon />,
  AsteriskSolid: <AsteriskSolidIcon />,
  Attach: <AttachIcon />,
  AustralianRules: <AustralianRulesIcon />,
  AutoDeploySettings: <AutoDeploySettingsIcon />,
  AutoEnhanceOff: <AutoEnhanceOffIcon />,
  AutoEnhanceOn: <AutoEnhanceOnIcon />,
  AutoFillTemplate: <AutoFillTemplateIcon />,
  AutoFitContents: <AutoFitContentsIcon />,
  AutoFitWindow: <AutoFitWindowIcon />,
  AutoHeight: <AutoHeightIcon />,
  AutomateFlow: <AutomateFlowIcon />,
  AutoRacing: <AutoRacingIcon />,
  AwayStatus: <AwayStatusIcon />,
  BackgroundColor: <BackgroundColorIcon />,
  Back: <BackIcon />,
  BacklogBoard: <BacklogBoardIcon />,
  Backlog: <BacklogIcon />,
  BacklogList: <BacklogListIcon />,
  BackToWindow: <BackToWindowIcon />,
  Badge: <BadgeIcon />,
  Balloons: <BalloonsIcon />,
  Bank: <BankIcon />,
  BankSolid: <BankSolidIcon />,
  BarChart4: <BarChart4Icon />,
  BarChartHorizontal: <BarChartHorizontalIcon />,
  BarChartVerticalEdit: <BarChartVerticalEditIcon />,
  BarChartVerticalFill: <BarChartVerticalFillIcon />,
  BarChartVerticalFilter: <BarChartVerticalFilterIcon />,
  BarChartVerticalFilterSolid: <BarChartVerticalFilterSolidIcon />,
  BarChartVertical: <BarChartVerticalIcon />,
  Baseball: <BaseballIcon />,
  BeerMug: <BeerMugIcon />,
  BIDashboard: <BIDashboardIcon />,
  BidiLtr: <BidiLtrIcon />,
  BidiRtl: <BidiRtlIcon />,
  BirthdayCake: <BirthdayCakeIcon />,
  BitbucketLogo32: <BitbucketLogo32Icon />,
  BlobStorage: <BlobStorageIcon />,
  BlockContact: <BlockContactIcon />,
  Blocked12: <Blocked12Icon />,
  Blocked2: <Blocked2Icon />,
  Blocked2Solid: <Blocked2SolidIcon />,
  Blocked: <BlockedIcon />,
  BlockedSite: <BlockedSiteIcon />,
  BlockedSiteSolid12: <BlockedSiteSolid12Icon />,
  BlockedSolid: <BlockedSolidIcon />,
  Blog: <BlogIcon />,
  BlowingSnow: <BlowingSnowIcon />,
  Blur: <BlurIcon />,
  Boards: <BoardsIcon />,
  Bold: <BoldIcon />,
  BookAnswers: <BookAnswersIcon />,
  BookmarkReport: <BookmarkReportIcon />,
  Bookmarks: <BookmarksIcon />,
  BookmarksMirrored: <BookmarksMirroredIcon />,
  BorderDash: <BorderDashIcon />,
  BorderDot: <BorderDotIcon />,
  BoxAdditionSolid: <BoxAdditionSolidIcon />,
  BoxCheckmarkSolid: <BoxCheckmarkSolidIcon />,
  BoxLogo: <BoxLogoIcon />,
  BoxMultiplySolid: <BoxMultiplySolidIcon />,
  BoxPlaySolid: <BoxPlaySolidIcon />,
  BoxSubtractSolid: <BoxSubtractSolidIcon />,
  BranchCommit: <BranchCommitIcon />,
  BranchCompare: <BranchCompareIcon />,
  BranchFork2: <BranchFork2Icon />,
  BranchFork: <BranchForkIcon />,
  BranchLocked: <BranchLockedIcon />,
  BranchMerge: <BranchMergeIcon />,
  BranchPullRequest: <BranchPullRequestIcon />,
  BranchSearch: <BranchSearchIcon />,
  BranchShelveset: <BranchShelvesetIcon />,
  Breadcrumb: <BreadcrumbIcon />,
  Breakfast: <BreakfastIcon />,
  Brightness: <BrightnessIcon />,
  Broom: <BroomIcon />,
  BrowserScreenShot: <BrowserScreenShotIcon />,
  BrowserTab: <BrowserTabIcon />,
  BrowserTabScreenshot: <BrowserTabScreenshotIcon />,
  Brunch: <BrunchIcon />,
  Brush: <BrushIcon />,
  BucketColorFill: <BucketColorFillIcon />,
  BucketColor: <BucketColorIcon />,
  BufferTimeAfter: <BufferTimeAfterIcon />,
  BufferTimeBefore: <BufferTimeBeforeIcon />,
  BufferTimeBoth: <BufferTimeBothIcon />,
  BugBlock: <BugBlockIcon />,
  Bug: <BugIcon />,
  BugSolid: <BugSolidIcon />,
  BugSync: <BugSyncIcon />,
  BuildDefinition: <BuildDefinitionIcon />,
  Build: <BuildIcon />,
  BuildIssue: <BuildIssueIcon />,
  BuildQueue: <BuildQueueIcon />,
  BuildQueueNew: <BuildQueueNewIcon />,
  BulkUpload: <BulkUploadIcon />,
  BulletedList2: <BulletedList2Icon />,
  BulletedList2Mirrored: <BulletedList2MirroredIcon />,
  BulletedListBullet: <BulletedListBulletIcon />,
  BulletedListBulletMirrored: <BulletedListBulletMirroredIcon />,
  BulletedList: <BulletedListIcon />,
  BulletedListMirrored: <BulletedListMirroredIcon />,
  BulletedListText: <BulletedListTextIcon />,
  BulletedListTextMirrored: <BulletedListTextMirroredIcon />,
  BulletedTreeList: <BulletedTreeListIcon />,
  Bullseye: <BullseyeIcon />,
  BullseyeTargetEdit: <BullseyeTargetEditIcon />,
  BullseyeTarget: <BullseyeTargetIcon />,
  Bus: <BusIcon />,
  BusinessHoursSign: <BusinessHoursSignIcon />,
  BusSolid: <BusSolidIcon />,
  ButtonControl: <ButtonControlIcon />,
  Cafe: <CafeIcon />,
  Cake: <CakeIcon />,
  CalculatorAddition: <CalculatorAdditionIcon />,
  CalculatorDelta: <CalculatorDeltaIcon />,
  CalculatorEqualTo: <CalculatorEqualToIcon />,
  CalculatorGroup: <CalculatorGroupIcon />,
  Calculator: <CalculatorIcon />,
  CalculatorMultiply: <CalculatorMultiplyIcon />,
  CalculatorNotEqualTo: <CalculatorNotEqualToIcon />,
  CalculatorPercentage: <CalculatorPercentageIcon />,
  CalculatorSubtract: <CalculatorSubtractIcon />,
  CalendarAgenda: <CalendarAgendaIcon />,
  CalendarDay: <CalendarDayIcon />,
  Calendar: <CalendarIcon />,
  CalendarMirrored: <CalendarMirroredIcon />,
  CalendarReply: <CalendarReplyIcon />,
  CalendarSettings: <CalendarSettingsIcon />,
  CalendarSettingsMirrored: <CalendarSettingsMirroredIcon />,
  CalendarWeek: <CalendarWeekIcon />,
  CalendarWorkWeek: <CalendarWorkWeekIcon />,
  CalendarYear: <CalendarYearIcon />,
  CaloriesAdd: <CaloriesAddIcon />,
  Calories: <CaloriesIcon />,
  Camera: <CameraIcon />,
  CampaignTemplate: <CampaignTemplateIcon />,
  Cancel: <CancelIcon />,
  CannedChat: <CannedChatIcon />,
  CaretBottomLeftCenter8: <CaretBottomLeftCenter8Icon />,
  CaretBottomLeftSolid8: <CaretBottomLeftSolid8Icon />,
  CaretBottomRightCenter8: <CaretBottomRightCenter8Icon />,
  CaretBottomRightSolid8: <CaretBottomRightSolid8Icon />,
  CaretDown8: <CaretDown8Icon />,
  CaretDownSolid8: <CaretDownSolid8Icon />,
  CaretHollow: <CaretHollowIcon />,
  CaretHollowMirrored: <CaretHollowMirroredIcon />,
  CaretLeft8: <CaretLeft8Icon />,
  CaretLeftSolid8: <CaretLeftSolid8Icon />,
  CaretRight8: <CaretRight8Icon />,
  CaretRight: <CaretRightIcon />,
  CaretRightSolid8: <CaretRightSolid8Icon />,
  CaretSolid16: <CaretSolid16Icon />,
  CaretSolidDown: <CaretSolidDownIcon />,
  CaretSolid: <CaretSolidIcon />,
  CaretSolidLeft: <CaretSolidLeftIcon />,
  CaretSolidMirrored: <CaretSolidMirroredIcon />,
  CaretSolidRight: <CaretSolidRightIcon />,
  CaretSolidUp: <CaretSolidUpIcon />,
  CaretTopLeftCenter8: <CaretTopLeftCenter8Icon />,
  CaretTopLeftSolid8: <CaretTopLeftSolid8Icon />,
  CaretTopRightCenter8: <CaretTopRightCenter8Icon />,
  CaretTopRightSolid8: <CaretTopRightSolid8Icon />,
  CaretUp8: <CaretUp8Icon />,
  CaretUpSolid8: <CaretUpSolid8Icon />,
  Car: <CarIcon />,
  Cat: <CatIcon />,
  CellPhone: <CellPhoneIcon />,
  Certificate: <CertificateIcon />,
  CertifiedDatabase: <CertifiedDatabaseIcon />,
  ChangeEntitlements: <ChangeEntitlementsIcon />,
  Chart: <ChartIcon />,
  ChartSeries: <ChartSeriesIcon />,
  ChartTemplate: <ChartTemplateIcon />,
  ChartXAngle: <ChartXAngleIcon />,
  ChartYAngle: <ChartYAngleIcon />,
  ChatBot: <ChatBotIcon />,
  Chat: <ChatIcon />,
  ChatInviteFriend: <ChatInviteFriendIcon />,
  ChatSolid: <ChatSolidIcon />,
  CheckboxComposite: <CheckboxCompositeIcon />,
  CheckboxCompositeReversed: <CheckboxCompositeReversedIcon />,
  CheckboxFill: <CheckboxFillIcon />,
  Checkbox: <CheckboxIcon />,
  CheckboxIndeterminate: <CheckboxIndeterminateIcon />,
  CheckedOutByOther12: <CheckedOutByOther12Icon />,
  CheckedOutByYou12: <CheckedOutByYou12Icon />,
  CheckListCheck: <CheckListCheckIcon />,
  CheckListCheckMirrored: <CheckListCheckMirroredIcon />,
  CheckList: <CheckListIcon />,
  CheckListText: <CheckListTextIcon />,
  CheckListTextMirrored: <CheckListTextMirroredIcon />,
  CheckMark: <CheckMarkIcon />,
  ChevronDownEnd6: <ChevronDownEnd6Icon />,
  ChevronDown: <ChevronDownIcon />,
  ChevronDownMed: <ChevronDownMedIcon />,
  ChevronDownSmall: <ChevronDownSmallIcon />,
  ChevronFold10: <ChevronFold10Icon />,
  ChevronLeftEnd6: <ChevronLeftEnd6Icon />,
  ChevronLeft: <ChevronLeftIcon />,
  ChevronLeftMed: <ChevronLeftMedIcon />,
  ChevronLeftSmall: <ChevronLeftSmallIcon />,
  ChevronRightEnd6: <ChevronRightEnd6Icon />,
  ChevronRight: <ChevronRightIcon />,
  ChevronRightMed: <ChevronRightMedIcon />,
  ChevronRightSmall: <ChevronRightSmallIcon />,
  ChevronUnfold10: <ChevronUnfold10Icon />,
  ChevronUpEnd6: <ChevronUpEnd6Icon />,
  ChevronUp: <ChevronUpIcon />,
  ChevronUpMed: <ChevronUpMedIcon />,
  ChevronUpSmall: <ChevronUpSmallIcon />,
  Childof: <ChildofIcon />,
  Chopsticks: <ChopsticksIcon />,
  ChromeBack: <ChromeBackIcon />,
  ChromeBackMirrored: <ChromeBackMirroredIcon />,
  ChromeClose: <ChromeCloseIcon />,
  ChromeFullScreen: <ChromeFullScreenIcon />,
  ChromeMinimize: <ChromeMinimizeIcon />,
  ChromeRestore: <ChromeRestoreIcon />,
  ChronosLogo: <ChronosLogoIcon />,
  CircleAddition: <CircleAdditionIcon />,
  CircleAdditionSolid: <CircleAdditionSolidIcon />,
  CircleFill: <CircleFillIcon />,
  CircleHalfFull: <CircleHalfFullIcon />,
  CirclePause: <CirclePauseIcon />,
  CirclePauseSolid: <CirclePauseSolidIcon />,
  CirclePlus: <CirclePlusIcon />,
  CircleRing: <CircleRingIcon />,
  CircleShape: <CircleShapeIcon />,
  CircleShapeSolid: <CircleShapeSolidIcon />,
  CircleStop: <CircleStopIcon />,
  CircleStopSolid: <CircleStopSolidIcon />,
  CityNext2: <CityNext2Icon />,
  CityNext: <CityNextIcon />,
  ClearFilter: <ClearFilterIcon />,
  ClearFormattingA: <ClearFormattingAIcon />,
  ClearFormattingEraser: <ClearFormattingEraserIcon />,
  ClearFormatting: <ClearFormattingIcon />,
  Clear: <ClearIcon />,
  ClearNight: <ClearNightIcon />,
  ClearSelection: <ClearSelectionIcon />,
  ClearSelectionMirrored: <ClearSelectionMirroredIcon />,
  ClipboardList: <ClipboardListIcon />,
  ClipboardListMirrored: <ClipboardListMirroredIcon />,
  ClipboardSolid: <ClipboardSolidIcon />,
  Clock: <ClockIcon />,
  CloneToDesktop: <CloneToDesktopIcon />,
  ClosedCaption: <ClosedCaptionIcon />,
  ClosePane: <ClosePaneIcon />,
  ClosePaneMirrored: <ClosePaneMirroredIcon />,
  CloudWeather: <CloudWeatherIcon />,
  Cloudy: <CloudyIcon />,
  Cocktails: <CocktailsIcon />,
  CodeEdit: <CodeEditIcon />,
  Code: <CodeIcon />,
  Coffee: <CoffeeIcon />,
  CoffeeScript: <CoffeeScriptIcon />,
  CollapseContent: <CollapseContentIcon />,
  CollapseContentSingle: <CollapseContentSingleIcon />,
  CollapseMenu: <CollapseMenuIcon />,
  CollegeFootball: <CollegeFootballIcon />,
  CollegeHoops: <CollegeHoopsIcon />,
  Color: <ColorIcon />,
  ColorSolid: <ColorSolidIcon />,
  Column: <ColumnIcon />,
  ColumnLeftTwoThirdsEdit: <ColumnLeftTwoThirdsEditIcon />,
  ColumnLeftTwoThirds: <ColumnLeftTwoThirdsIcon />,
  ColumnOptions: <ColumnOptionsIcon />,
  ColumnRightTwoThirdsEdit: <ColumnRightTwoThirdsEditIcon />,
  ColumnRightTwoThirds: <ColumnRightTwoThirdsIcon />,
  ColumnVerticalSectionEdit: <ColumnVerticalSectionEditIcon />,
  ColumnVerticalSection: <ColumnVerticalSectionIcon />,
  Combine: <CombineIcon />,
  Combobox: <ComboboxIcon />,
  CommandPrompt: <CommandPromptIcon />,
  CommentActive: <CommentActiveIcon />,
  CommentAdd: <CommentAddIcon />,
  Comment: <CommentIcon />,
  CommentNext: <CommentNextIcon />,
  CommentPrevious: <CommentPreviousIcon />,
  CommentSolid: <CommentSolidIcon />,
  CommentUrgent: <CommentUrgentIcon />,
  Commitments: <CommitmentsIcon />,
  CommonDataServiceCDS: <CommonDataServiceCDSIcon />,
  Communications: <CommunicationsIcon />,
  CompanyDirectory: <CompanyDirectoryIcon />,
  CompanyDirectoryMirrored: <CompanyDirectoryMirroredIcon />,
  Compare: <CompareIcon />,
  CompareUneven: <CompareUnevenIcon />,
  CompassNW: <CompassNWIcon />,
  Completed: <CompletedIcon />,
  CompletedSolid: <CompletedSolidIcon />,
  ComplianceAudit: <ComplianceAuditIcon />,
  ConfigurationSolid: <ConfigurationSolidIcon />,
  ConnectContacts: <ConnectContactsIcon />,
  ConnectVirtualMachine: <ConnectVirtualMachineIcon />,
  ConstructionCone: <ConstructionConeIcon />,
  ConstructionConeSolid: <ConstructionConeSolidIcon />,
  ContactCard: <ContactCardIcon />,
  ContactCardSettings: <ContactCardSettingsIcon />,
  ContactCardSettingsMirrored: <ContactCardSettingsMirroredIcon />,
  ContactHeart: <ContactHeartIcon />,
  Contact: <ContactIcon />,
  ContactInfo: <ContactInfoIcon />,
  ContactLink: <ContactLinkIcon />,
  ContactList: <ContactListIcon />,
  ContactLock: <ContactLockIcon />,
  ContentFeed: <ContentFeedIcon />,
  ContentSettings: <ContentSettingsIcon />,
  ContextMenu: <ContextMenuIcon />,
  Contrast: <ContrastIcon />,
  CopyEdit: <CopyEditIcon />,
  Copy: <CopyIcon />,
  Cotton: <CottonIcon />,
  Coupon: <CouponIcon />,
  CPlusPlus: <CPlusPlusIcon />,
  CPlusPlusLanguage: <CPlusPlusLanguageIcon />,
  CreateMailRule: <CreateMailRuleIcon />,
  Cricket: <CricketIcon />,
  CRMProcesses: <CRMProcessesIcon />,
  CRMReport: <CRMReportIcon />,
  CRMServices: <CRMServicesIcon />,
  Crop: <CropIcon />,
  Crown: <CrownIcon />,
  CrownSolid: <CrownSolidIcon />,
  CSS: <CSSIcon />,
  CubeShape: <CubeShapeIcon />,
  CubeShapeSolid: <CubeShapeSolidIcon />,
  Currency: <CurrencyIcon />,
  CustomizeToolbar: <CustomizeToolbarIcon />,
  CustomList: <CustomListIcon />,
  CustomListMirrored: <CustomListMirroredIcon />,
  Cut: <CutIcon />,
  Cycling: <CyclingIcon />,
  DashboardAdd: <DashboardAddIcon />,
  Database: <DatabaseIcon />,
  DatabaseSync: <DatabaseSyncIcon />,
  DatabaseView: <DatabaseViewIcon />,
  DataConnectionLibrary: <DataConnectionLibraryIcon />,
  Dataflows: <DataflowsIcon />,
  DataflowsLink: <DataflowsLinkIcon />,
  DataManagementSettings: <DataManagementSettingsIcon />,
  DateTime12: <DateTime12Icon />,
  DateTime2: <DateTime2Icon />,
  DateTime: <DateTimeIcon />,
  DateTimeMirrored: <DateTimeMirroredIcon />,
  DeactivateOrders: <DeactivateOrdersIcon />,
  Decimals: <DecimalsIcon />,
  DecisionSolid: <DecisionSolidIcon />,
  DeclineCall: <DeclineCallIcon />,
  DecreaseIndentArrow: <DecreaseIndentArrowIcon />,
  DecreaseIndentArrowMirrored: <DecreaseIndentArrowMirroredIcon />,
  DecreaseIndent: <DecreaseIndentIcon />,
  DecreaseIndentLegacy: <DecreaseIndentLegacyIcon />,
  DecreaseIndentMirrored: <DecreaseIndentMirroredIcon />,
  DecreaseIndentText: <DecreaseIndentTextIcon />,
  DecreaseIndentTextMirrored: <DecreaseIndentTextMirroredIcon />,
  DefaultRatio: <DefaultRatioIcon />,
  DefectSolid: <DefectSolidIcon />,
  DeleteColumns: <DeleteColumnsIcon />,
  Delete: <DeleteIcon />,
  DeleteRows: <DeleteRowsIcon />,
  DeleteRowsMirrored: <DeleteRowsMirroredIcon />,
  DeleteTable: <DeleteTableIcon />,
  DeliveryTruck: <DeliveryTruckIcon />,
  DependencyAdd: <DependencyAddIcon />,
  DependencyRemove: <DependencyRemoveIcon />,
  Deploy: <DeployIcon />,
  Descending: <DescendingIcon />,
  Design: <DesignIcon />,
  DesktopScreenshot: <DesktopScreenshotIcon />,
  DeveloperTools: <DeveloperToolsIcon />,
  DeviceBug: <DeviceBugIcon />,
  DeviceOff: <DeviceOffIcon />,
  DeviceRun: <DeviceRunIcon />,
  Devices2: <Devices2Icon />,
  Devices3: <Devices3Icon />,
  Devices4: <Devices4Icon />,
  DiagnosticDataBarTooltip: <DiagnosticDataBarTooltipIcon />,
  Diagnostic: <DiagnosticIcon />,
  Dialpad: <DialpadIcon />,
  Diamond: <DiamondIcon />,
  DiamondSolid: <DiamondSolidIcon />,
  Dictionary: <DictionaryIcon />,
  DictionaryRemove: <DictionaryRemoveIcon />,
  DietPlanNotebook: <DietPlanNotebookIcon />,
  DiffInline: <DiffInlineIcon />,
  DiffSideBySide: <DiffSideBySideIcon />,
  DisableUpdates: <DisableUpdatesIcon />,
  DisconnectVirtualMachine: <DisconnectVirtualMachineIcon />,
  Dislike: <DislikeIcon />,
  DislikeSolid: <DislikeSolidIcon />,
  DistributeDown: <DistributeDownIcon />,
  DockerLogo: <DockerLogoIcon />,
  DockLeft: <DockLeftIcon />,
  DockLeftMirrored: <DockLeftMirroredIcon />,
  DockRight: <DockRightIcon />,
  DocLibrary: <DocLibraryIcon />,
  DocumentApproval: <DocumentApprovalIcon />,
  Documentation: <DocumentationIcon />,
  Document: <DocumentIcon />,
  DocumentManagement: <DocumentManagementIcon />,
  DocumentReply: <DocumentReplyIcon />,
  DocumentSearch: <DocumentSearchIcon />,
  DocumentSet: <DocumentSetIcon />,
  DOM: <DOMIcon />,
  DonutChart: <DonutChartIcon />,
  Door: <DoorIcon />,
  DoubleBookmark: <DoubleBookmarkIcon />,
  DoubleChevronDown12: <DoubleChevronDown12Icon />,
  DoubleChevronDown8: <DoubleChevronDown8Icon />,
  DoubleChevronDown: <DoubleChevronDownIcon />,
  DoubleChevronLeft12: <DoubleChevronLeft12Icon />,
  DoubleChevronLeft8: <DoubleChevronLeft8Icon />,
  DoubleChevronLeft: <DoubleChevronLeftIcon />,
  DoubleChevronLeftMed: <DoubleChevronLeftMedIcon />,
  DoubleChevronLeftMedMirrored: <DoubleChevronLeftMedMirroredIcon />,
  DoubleChevronRight12: <DoubleChevronRight12Icon />,
  DoubleChevronRight8: <DoubleChevronRight8Icon />,
  DoubleChevronRight: <DoubleChevronRightIcon />,
  DoubleChevronUp12: <DoubleChevronUp12Icon />,
  DoubleChevronUp8: <DoubleChevronUp8Icon />,
  DoubleChevronUp: <DoubleChevronUpIcon />,
  DoubleColumnEdit: <DoubleColumnEditIcon />,
  DoubleColumn: <DoubleColumnIcon />,
  DoubleDownArrow: <DoubleDownArrowIcon />,
  Down: <DownIcon />,
  DownloadDocument: <DownloadDocumentIcon />,
  Download: <DownloadIcon />,
  DragObject: <DragObjectIcon />,
  DrillDown: <DrillDownIcon />,
  DrillDownSolid: <DrillDownSolidIcon />,
  DrillExpand: <DrillExpandIcon />,
  DrillShow: <DrillShowIcon />,
  DrillThrough: <DrillThroughIcon />,
  DriverOff: <DriverOffIcon />,
  DRM: <DRMIcon />,
  DropboxLogo: <DropboxLogoIcon />,
  Dropdown: <DropdownIcon />,
  Drop: <DropIcon />,
  DropShape: <DropShapeIcon />,
  DropShapeSolid: <DropShapeSolidIcon />,
  DuplicateRow: <DuplicateRowIcon />,
  Duststorm: <DuststormIcon />,
  EatDrink: <EatDrinkIcon />,
  EditContact: <EditContactIcon />,
  EditCreate: <EditCreateIcon />,
  Edit: <EditIcon />,
  EditMail: <EditMailIcon />,
  EditMirrored: <EditMirroredIcon />,
  EditNote: <EditNoteIcon />,
  EditPhoto: <EditPhotoIcon />,
  EditSolid12: <EditSolid12Icon />,
  EditSolidMirrored12: <EditSolidMirrored12Icon />,
  EditStyle: <EditStyleIcon />,
  Education: <EducationIcon />,
  EgnyteLogo: <EgnyteLogoIcon />,
  Ellipse: <EllipseIcon />,
  Embed: <EmbedIcon />,
  EMI: <EMIIcon />,
  Emoji2: <Emoji2Icon />,
  EmojiDisappointed: <EmojiDisappointedIcon />,
  Emoji: <EmojiIcon />,
  EmojiNeutral: <EmojiNeutralIcon />,
  EmojiTabSymbols: <EmojiTabSymbolsIcon />,
  EmptyRecycleBin: <EmptyRecycleBinIcon />,
  Encryption: <EncryptionIcon />,
  EndPointSolid: <EndPointSolidIcon />,
  EngineeringGroup: <EngineeringGroupIcon />,
  EntitlementPolicy: <EntitlementPolicyIcon />,
  EntitlementRedemption: <EntitlementRedemptionIcon />,
  EntryDecline: <EntryDeclineIcon />,
  EntryView: <EntryViewIcon />,
  Equalizer: <EqualizerIcon />,
  EraseTool: <EraseToolIcon />,
  ErrorBadge: <ErrorBadgeIcon />,
  Error: <ErrorIcon />,
  Event12: <Event12Icon />,
  EventAccepted: <EventAcceptedIcon />,
  EventDate: <EventDateIcon />,
  EventDateMissed12: <EventDateMissed12Icon />,
  EventDeclined: <EventDeclinedIcon />,
  Event: <EventIcon />,
  EventInfo: <EventInfoIcon />,
  EventTentative: <EventTentativeIcon />,
  EventTentativeMirrored: <EventTentativeMirroredIcon />,
  EventToDoLogo: <EventToDoLogoIcon />,
  ExerciseTracker: <ExerciseTrackerIcon />,
  ExpandMenu: <ExpandMenuIcon />,
  ExploreContent: <ExploreContentIcon />,
  ExploreContentSingle: <ExploreContentSingleIcon />,
  ExploreData: <ExploreDataIcon />,
  Export: <ExportIcon />,
  ExportMirrored: <ExportMirroredIcon />,
  ExternalBuild: <ExternalBuildIcon />,
  ExternalGit: <ExternalGitIcon />,
  ExternalTFVC: <ExternalTFVCIcon />,
  ExternalXAML: <ExternalXAMLIcon />,
  Eyedropper: <EyedropperIcon />,
  EyeShadow: <EyeShadowIcon />,
  F12DevTools: <F12DevToolsIcon />,
  FacebookLogo: <FacebookLogoIcon />,
  Family: <FamilyIcon />,
  FangBody: <FangBodyIcon />,
  FastForwardEightX: <FastForwardEightXIcon />,
  FastForwardFourX: <FastForwardFourXIcon />,
  FastForward: <FastForwardIcon />,
  FastForwardOneFiveX: <FastForwardOneFiveXIcon />,
  FastForwardOneX: <FastForwardOneXIcon />,
  FastForwardPointFiveX: <FastForwardPointFiveXIcon />,
  FastForwardTwoX: <FastForwardTwoXIcon />,
  FastMode: <FastModeIcon />,
  Favicon: <FaviconIcon />,
  FavoriteList: <FavoriteListIcon />,
  FavoriteStarFill: <FavoriteStarFillIcon />,
  FavoriteStar: <FavoriteStarIcon />,
  Fax: <FaxIcon />,
  Feedback: <FeedbackIcon />,
  FeedbackRequestMirroredSolid: <FeedbackRequestMirroredSolidIcon />,
  FeedbackRequestSolid: <FeedbackRequestSolidIcon />,
  FeedbackResponseSolid: <FeedbackResponseSolidIcon />,
  Ferry: <FerryIcon />,
  FerrySolid: <FerrySolidIcon />,
  FieldChanged: <FieldChangedIcon />,
  FieldEmpty: <FieldEmptyIcon />,
  FieldFilled: <FieldFilledIcon />,
  FieldNotChanged: <FieldNotChangedIcon />,
  FieldReadOnly: <FieldReadOnlyIcon />,
  FieldRequired: <FieldRequiredIcon />,
  FileASPX: <FileASPXIcon />,
  FileBug: <FileBugIcon />,
  FileCode: <FileCodeIcon />,
  FileComment: <FileCommentIcon />,
  FileCSS: <FileCSSIcon />,
  FileHTML: <FileHTMLIcon />,
  FileImage: <FileImageIcon />,
  FileJAVA: <FileJAVAIcon />,
  FileLess: <FileLessIcon />,
  FileOff: <FileOffIcon />,
  FilePDB: <FilePDBIcon />,
  FileRequest: <FileRequestIcon />,
  FileSass: <FileSassIcon />,
  FileSQL: <FileSQLIcon />,
  FileSymlink: <FileSymlinkIcon />,
  FileSystem: <FileSystemIcon />,
  FileTemplate: <FileTemplateIcon />,
  FileYML: <FileYMLIcon />,
  FilterAscending: <FilterAscendingIcon />,
  FilterDescending: <FilterDescendingIcon />,
  Filter: <FilterIcon />,
  FilterSettings: <FilterSettingsIcon />,
  Filters: <FiltersIcon />,
  FilterSolid: <FilterSolidIcon />,
  FiltersSolid: <FiltersSolidIcon />,
  Financial: <FinancialIcon />,
  FinancialMirroredSolid: <FinancialMirroredSolidIcon />,
  FinancialSolid: <FinancialSolidIcon />,
  Fingerprint: <FingerprintIcon />,
  FitPage: <FitPageIcon />,
  FitWidth: <FitWidthIcon />,
  FiveTileGrid: <FiveTileGridIcon />,
  FixedAssetManagement: <FixedAssetManagementIcon />,
  FixedColumnWidth: <FixedColumnWidthIcon />,
  Flag: <FlagIcon />,
  FlameSolid: <FlameSolidIcon />,
  FlashAuto: <FlashAutoIcon />,
  Flashlight: <FlashlightIcon />,
  FlashOff: <FlashOffIcon />,
  FlickDown: <FlickDownIcon />,
  FlickLeft: <FlickLeftIcon />,
  FlickRight: <FlickRightIcon />,
  FlickUp: <FlickUpIcon />,
  FlowChart: <FlowChartIcon />,
  Flower: <FlowerIcon />,
  Flow: <FlowIcon />,
  FocalPoint: <FocalPointIcon />,
  Focus: <FocusIcon />,
  FocusView: <FocusViewIcon />,
  Fog: <FogIcon />,
  FolderFill: <FolderFillIcon />,
  FolderHorizontal: <FolderHorizontalIcon />,
  Folder: <FolderIcon />,
  FolderList: <FolderListIcon />,
  FolderListMirrored: <FolderListMirroredIcon />,
  FolderOpen: <FolderOpenIcon />,
  FolderQuery: <FolderQueryIcon />,
  FolderSearch: <FolderSearchIcon />,
  FollowUser: <FollowUserIcon />,
  FontColorA: <FontColorAIcon />,
  FontColor: <FontColorIcon />,
  FontColorSwatch: <FontColorSwatchIcon />,
  FontDecrease: <FontDecreaseIcon />,
  Font: <FontIcon />,
  FontIncrease: <FontIncreaseIcon />,
  FontSize2: <FontSize2Icon />,
  FontSize: <FontSizeIcon />,
  Footer: <FooterIcon />,
  FormatPainter: <FormatPainterIcon />,
  FormLibrary: <FormLibraryIcon />,
  FormLibraryMirrored: <FormLibraryMirroredIcon />,
  Forum: <ForumIcon />,
  ForwardEvent: <ForwardEventIcon />,
  Forward: <ForwardIcon />,
  Freezing: <FreezingIcon />,
  Frigid: <FrigidIcon />,
  FrontCamera: <FrontCameraIcon />,
  FullCircleMask: <FullCircleMaskIcon />,
  FullHistory: <FullHistoryIcon />,
  FullScreen: <FullScreenIcon />,
  FullView: <FullViewIcon />,
  FullWidthEdit: <FullWidthEditIcon />,
  FullWidth: <FullWidthIcon />,
  FunctionalManagerDashboard: <FunctionalManagerDashboardIcon />,
  FunnelChart: <FunnelChartIcon />,
  Game: <GameIcon />,
  Gather: <GatherIcon />,
  Generate: <GenerateIcon />,
  GenericScanFilled: <GenericScanFilledIcon />,
  GenericScan: <GenericScanIcon />,
  GIF: <GIFIcon />,
  Giftbox: <GiftboxIcon />,
  GiftboxOpen: <GiftboxOpenIcon />,
  GiftBoxSolid: <GiftBoxSolidIcon />,
  GiftCard: <GiftCardIcon />,
  GitFork: <GitForkIcon />,
  GitGraph: <GitGraphIcon />,
  GitHubLogo: <GitHubLogoIcon />,
  GitLogo: <GitLogoIcon />,
  Glasses: <GlassesIcon />,
  Glimmer: <GlimmerIcon />,
  GlobalNavButtonActive: <GlobalNavButtonActiveIcon />,
  GlobalNavButton: <GlobalNavButtonIcon />,
  Globe2: <Globe2Icon />,
  GlobeFavorite: <GlobeFavoriteIcon />,
  Globe: <GlobeIcon />,
  Go: <GoIcon />,
  Golf: <GolfIcon />,
  GoMirrored: <GoMirroredIcon />,
  GoogleDriveLogoBottomBlue: <GoogleDriveLogoBottomBlueIcon />,
  GoogleDriveLogo: <GoogleDriveLogoIcon />,
  GoogleDriveLogoLeftGreen: <GoogleDriveLogoLeftGreenIcon />,
  GoogleDriveLogoRightYellow: <GoogleDriveLogoRightYellowIcon />,
  GoToDashboard: <GoToDashboardIcon />,
  GotoToday: <GotoTodayIcon />,
  GradleLogo32: <GradleLogo32Icon />,
  GreetingCard: <GreetingCardIcon />,
  GridViewLarge: <GridViewLargeIcon />,
  GridViewMedium: <GridViewMediumIcon />,
  GridViewSmall: <GridViewSmallIcon />,
  GripperBarHorizontal: <GripperBarHorizontalIcon />,
  GripperBarVertical: <GripperBarVerticalIcon />,
  GripperDotsVertical: <GripperDotsVerticalIcon />,
  GripperTool: <GripperToolIcon />,
  GroupedAscending: <GroupedAscendingIcon />,
  GroupedDescending: <GroupedDescendingIcon />,
  GroupedList: <GroupedListIcon />,
  Group: <GroupIcon />,
  GroupList: <GroupListIcon />,
  GroupObject: <GroupObjectIcon />,
  GUID: <GUIDIcon />,
  Guitar: <GuitarIcon />,
  HailDay: <HailDayIcon />,
  HailNight: <HailNightIcon />,
  HalfAlpha: <HalfAlphaIcon />,
  HalfCircle: <HalfCircleIcon />,
  HandsFree: <HandsFreeIcon />,
  Handwriting: <HandwritingIcon />,
  HardDriveGroup: <HardDriveGroupIcon />,
  HardDrive: <HardDriveIcon />,
  HardDriveLock: <HardDriveLockIcon />,
  HardDriveUnlock: <HardDriveUnlockIcon />,
  Header1: <Header1Icon />,
  Header2: <Header2Icon />,
  Header3: <Header3Icon />,
  Header4: <Header4Icon />,
  Header: <HeaderIcon />,
  Headset: <HeadsetIcon />,
  HeadsetSolid: <HeadsetSolidIcon />,
  Health: <HealthIcon />,
  HealthRefresh: <HealthRefreshIcon />,
  HealthSolid: <HealthSolidIcon />,
  HeartBroken: <HeartBrokenIcon />,
  HeartFill: <HeartFillIcon />,
  Heart: <HeartIcon />,
  Help: <HelpIcon />,
  HelpMirrored: <HelpMirroredIcon />,
  HexaditeInvestigationCancel: <HexaditeInvestigationCancelIcon />,
  HexaditeInvestigation: <HexaditeInvestigationIcon />,
  HexaditeInvestigationSemiAuto: <HexaditeInvestigationSemiAutoIcon />,
  Hexagon: <HexagonIcon />,
  Hide2: <Hide2Icon />,
  Hide3: <Hide3Icon />,
  Hide: <HideIcon />,
  Highlight: <HighlightIcon />,
  HighlightMappedShapes: <HighlightMappedShapesIcon />,
  HintText: <HintTextIcon />,
  HistoricalWeather: <HistoricalWeatherIcon />,
  History: <HistoryIcon />,
  HomeDropdown: <HomeDropdownIcon />,
  HomeGroup: <HomeGroupIcon />,
  Home: <HomeIcon />,
  HomeSolid: <HomeSolidIcon />,
  HomeVerify: <HomeVerifyIcon />,
  HorizontalDistributeCenter: <HorizontalDistributeCenterIcon />,
  HorizontalTabKey: <HorizontalTabKeyIcon />,
  Hospital: <HospitalIcon />,
  Hotel: <HotelIcon />,
  HourGlass: <HourGlassIcon />,
  IconSetsFlag: <IconSetsFlagIcon />,
  IDBadge: <IDBadgeIcon />,
  IgnoreConversation: <IgnoreConversationIcon />,
  ImageCrosshair: <ImageCrosshairIcon />,
  ImageDiff: <ImageDiffIcon />,
  ImageInAR: <ImageInARIcon />,
  ImagePixel: <ImagePixelIcon />,
  ImageSearch: <ImageSearchIcon />,
  ImportAllMirrored: <ImportAllMirroredIcon />,
  Important: <ImportantIcon />,
  Import: <ImportIcon />,
  ImportMirrored: <ImportMirroredIcon />,
  InboxCheck: <InboxCheckIcon />,
  Inbox: <InboxIcon />,
  IncidentTriangle: <IncidentTriangleIcon />,
  IncomingCall: <IncomingCallIcon />,
  IncreaseIndentArrow: <IncreaseIndentArrowIcon />,
  IncreaseIndentArrowMirrored: <IncreaseIndentArrowMirroredIcon />,
  IncreaseIndentHanging: <IncreaseIndentHangingIcon />,
  IncreaseIndentHangingMirrored: <IncreaseIndentHangingMirroredIcon />,
  IncreaseIndent: <IncreaseIndentIcon />,
  IncreaseIndentLegacy: <IncreaseIndentLegacyIcon />,
  IncreaseIndentMirrored: <IncreaseIndentMirroredIcon />,
  IncreaseIndentText: <IncreaseIndentTextIcon />,
  IncreaseIndentTextMirrored: <IncreaseIndentTextMirroredIcon />,
  IndentFirstLine: <IndentFirstLineIcon />,
  Info2: <Info2Icon />,
  Info: <InfoIcon />,
  InformationBarriers: <InformationBarriersIcon />,
  InfoSolid: <InfoSolidIcon />,
  InkingTool: <InkingToolIcon />,
  InputAddress: <InputAddressIcon />,
  InsertColumnsLeft: <InsertColumnsLeftIcon />,
  InsertColumnsRight: <InsertColumnsRightIcon />,
  Insert: <InsertIcon />,
  InsertRowsAbove: <InsertRowsAboveIcon />,
  InsertRowsBelow: <InsertRowsBelowIcon />,
  InsertSignatureLine: <InsertSignatureLineIcon />,
  InsertTextBox: <InsertTextBoxIcon />,
  Insights: <InsightsIcon />,
  Installation: <InstallationIcon />,
  InstallToDrive: <InstallToDriveIcon />,
  InternalInvestigation: <InternalInvestigationIcon />,
  InternetSharing: <InternetSharingIcon />,
  IOT: <IOTIcon />,
  IRMForward: <IRMForwardIcon />,
  IRMForwardMirrored: <IRMForwardMirroredIcon />,
  IRMReply: <IRMReplyIcon />,
  IRMReplyMirrored: <IRMReplyMirroredIcon />,
  IssueSolid: <IssueSolidIcon />,
  IssueTracking: <IssueTrackingIcon />,
  IssueTrackingMirrored: <IssueTrackingMirroredIcon />,
  Italic: <ItalicIcon />,
  JavaLogo: <JavaLogoIcon />,
  JavaScriptLanguage: <JavaScriptLanguageIcon />,
  JenkinsLogo: <JenkinsLogoIcon />,
  JoinOnlineMeeting: <JoinOnlineMeetingIcon />,
  JS: <JSIcon />,
  KeubernetesLogo: <KeubernetesLogoIcon />,
  KeyboardClassic: <KeyboardClassicIcon />,
  KeyPhraseExtraction: <KeyPhraseExtractionIcon />,
  KnowledgeArticle: <KnowledgeArticleIcon />,
  Label: <LabelIcon />,
  LadybugSolid: <LadybugSolidIcon />,
  Lamp: <LampIcon />,
  LandscapeOrientation: <LandscapeOrientationIcon />,
  LaptopSecure: <LaptopSecureIcon />,
  LaptopSelected: <LaptopSelectedIcon />,
  LargeGrid: <LargeGridIcon />,
  LearningTools: <LearningToolsIcon />,
  Leave: <LeaveIcon />,
  LeaveUser: <LeaveUserIcon />,
  Library: <LibraryIcon />,
  Lifesaver: <LifesaverIcon />,
  LifesaverLock: <LifesaverLockIcon />,
  Lightbulb: <LightbulbIcon />,
  Light: <LightIcon />,
  LightningBolt: <LightningBoltIcon />,
  LightningBoltSolid: <LightningBoltSolidIcon />,
  LightWeight: <LightWeightIcon />,
  Like: <LikeIcon />,
  LikeSolid: <LikeSolidIcon />,
  LineChart: <LineChartIcon />,
  Line: <LineIcon />,
  LineSpacing: <LineSpacingIcon />,
  LineStyle: <LineStyleIcon />,
  LineThickness: <LineThicknessIcon />,
  Link12: <Link12Icon />,
  LinkedDatabase: <LinkedDatabaseIcon />,
  Link: <LinkIcon />,
  LinuxLogo32: <LinuxLogo32Icon />,
  List: <ListIcon />,
  ListMirrored: <ListMirroredIcon />,
  LiveSite: <LiveSiteIcon />,
  LocaleLanguage: <LocaleLanguageIcon />,
  LocationCircle: <LocationCircleIcon />,
  LocationDot: <LocationDotIcon />,
  LocationFill: <LocationFillIcon />,
  Location: <LocationIcon />,
  LocationOutline: <LocationOutlineIcon />,
  Lock12: <Lock12Icon />,
  Lock: <LockIcon />,
  LockShare: <LockShareIcon />,
  LockSolid: <LockSolidIcon />,
  LogRemove: <LogRemoveIcon />,
  LookupEntities: <LookupEntitiesIcon />,
  LowerBrightness: <LowerBrightnessIcon />,
  MachineLearning: <MachineLearningIcon />,
  MailAlert: <MailAlertIcon />,
  MailAttached: <MailAttachedIcon />,
  MailCheck: <MailCheckIcon />,
  MailFill: <MailFillIcon />,
  MailForward: <MailForwardIcon />,
  MailForwardMirrored: <MailForwardMirroredIcon />,
  Mail: <MailIcon />,
  MailLowImportance: <MailLowImportanceIcon />,
  MailOptions: <MailOptionsIcon />,
  MailPause: <MailPauseIcon />,
  MailReminder: <MailReminderIcon />,
  MailRepeat: <MailRepeatIcon />,
  MailReplyAll: <MailReplyAllIcon />,
  MailReplyAllMirrored: <MailReplyAllMirroredIcon />,
  MailReply: <MailReplyIcon />,
  MailReplyMirrored: <MailReplyMirroredIcon />,
  MailSchedule: <MailScheduleIcon />,
  MailSolid: <MailSolidIcon />,
  MailTentative: <MailTentativeIcon />,
  MailTentativeMirrored: <MailTentativeMirroredIcon />,
  MailUndelivered: <MailUndeliveredIcon />,
  ManagerSelfService: <ManagerSelfServiceIcon />,
  Manufacturing: <ManufacturingIcon />,
  MapDirections: <MapDirectionsIcon />,
  MapLayers: <MapLayersIcon />,
  MapPin12: <MapPin12Icon />,
  MapPin: <MapPinIcon />,
  MapPinSolid: <MapPinSolidIcon />,
  MarkAsProtected: <MarkAsProtectedIcon />,
  MarkDownLanguage: <MarkDownLanguageIcon />,
  MarketDown: <MarketDownIcon />,
  Market: <MarketIcon />,
  MasterDatabase: <MasterDatabaseIcon />,
  MaximumValue: <MaximumValueIcon />,
  Medal: <MedalIcon />,
  MedalSolid: <MedalSolidIcon />,
  MediaAdd: <MediaAddIcon />,
  Media: <MediaIcon />,
  Medical: <MedicalIcon />,
  Megaphone: <MegaphoneIcon />,
  MegaphoneSolid: <MegaphoneSolidIcon />,
  Memo: <MemoIcon />,
  MergeDuplicate: <MergeDuplicateIcon />,
  Merge: <MergeIcon />,
  MessageFill: <MessageFillIcon />,
  MessageFriendRequest: <MessageFriendRequestIcon />,
  Message: <MessageIcon />,
  MicOff2: <MicOff2Icon />,
  MicOff: <MicOffIcon />,
  Microphone: <MicrophoneIcon />,
  MiniContract: <MiniContractIcon />,
  MiniContractMirrored: <MiniContractMirroredIcon />,
  MiniExpand: <MiniExpandIcon />,
  MiniExpandMirrored: <MiniExpandMirroredIcon />,
  MiniLink: <MiniLinkIcon />,
  MinimumValue: <MinimumValueIcon />,
  MiracastLogoLarge: <MiracastLogoLargeIcon />,
  MobileAngled: <MobileAngledIcon />,
  MobileReport: <MobileReportIcon />,
  MobileSelected: <MobileSelectedIcon />,
  ModelingView: <ModelingViewIcon />,
  Money: <MoneyIcon />,
  More: <MoreIcon />,
  MoreSports: <MoreSportsIcon />,
  MoreVertical: <MoreVerticalIcon />,
  MountainClimbing: <MountainClimbingIcon />,
  Move: <MoveIcon />,
  Movers: <MoversIcon />,
  MoveToFolder: <MoveToFolderIcon />,
  MultiSelect: <MultiSelectIcon />,
  MultiSelectMirrored: <MultiSelectMirroredIcon />,
  MusicInCollectionFill: <MusicInCollectionFillIcon />,
  MusicInCollection: <MusicInCollectionIcon />,
  MusicNote: <MusicNoteIcon />,
  MuteChat: <MuteChatIcon />,
  MyMoviesTV: <MyMoviesTVIcon />,
  MyNetwork: <MyNetworkIcon />,
  Nav2DMapView: <Nav2DMapViewIcon />,
  NavigateBack: <NavigateBackIcon />,
  NavigateBackMirrored: <NavigateBackMirroredIcon />,
  NavigateExternalInline: <NavigateExternalInlineIcon />,
  NavigateForward: <NavigateForwardIcon />,
  NavigateForwardMirrored: <NavigateForwardMirroredIcon />,
  NavigationFlipper: <NavigationFlipperIcon />,
  NetworkTower: <NetworkTowerIcon />,
  NewAnalyticsQuery: <NewAnalyticsQueryIcon />,
  NewFolder: <NewFolderIcon />,
  NewMail: <NewMailIcon />,
  News: <NewsIcon />,
  NewsSearch: <NewsSearchIcon />,
  NewTeamProject: <NewTeamProjectIcon />,
  Next: <NextIcon />,
  NonprofitLogo32: <NonprofitLogo32Icon />,
  NormalWeight: <NormalWeightIcon />,
  NoteForward: <NoteForwardIcon />,
  NotePinned: <NotePinnedIcon />,
  NoteReply: <NoteReplyIcon />,
  NotExecuted: <NotExecutedIcon />,
  NotImpactedSolid: <NotImpactedSolidIcon />,
  NPMLogo: <NPMLogoIcon />,
  NumberedList: <NumberedListIcon />,
  NumberedListMirrored: <NumberedListMirroredIcon />,
  NumberedListNumber: <NumberedListNumberIcon />,
  NumberedListNumberMirrored: <NumberedListNumberMirroredIcon />,
  NumberedListText: <NumberedListTextIcon />,
  NumberedListTextMirrored: <NumberedListTextMirroredIcon />,
  NumberField: <NumberFieldIcon />,
  Number: <NumberIcon />,
  NumberSequence: <NumberSequenceIcon />,
  NumberSymbol: <NumberSymbolIcon />,
  Octagon: <OctagonIcon />,
  OEM: <OEMIcon />,
  OfficeChat: <OfficeChatIcon />,
  OfficeChatSolid: <OfficeChatSolidIcon />,
  OfflineStorage: <OfflineStorageIcon />,
  OfflineStorageSolid: <OfflineStorageSolidIcon />,
  Onboarding: <OnboardingIcon />,
  OpenEnrollment: <OpenEnrollmentIcon />,
  OpenFile: <OpenFileIcon />,
  OpenFolderHorizontal: <OpenFolderHorizontalIcon />,
  OpenInNewTab: <OpenInNewTabIcon />,
  OpenInNewWindow: <OpenInNewWindowIcon />,
  OpenPane: <OpenPaneIcon />,
  OpenPaneMirrored: <OpenPaneMirroredIcon />,
  OpenSource: <OpenSourceIcon />,
  OpenWith: <OpenWithIcon />,
  OpenWithMirrored: <OpenWithMirroredIcon />,
  Org: <OrgIcon />,
  Orientation2: <Orientation2Icon />,
  Orientation: <OrientationIcon />,
  OutOfOffice: <OutOfOfficeIcon />,
  Package: <PackageIcon />,
  Packages: <PackagesIcon />,
  PaddingBottom: <PaddingBottomIcon />,
  Padding: <PaddingIcon />,
  PaddingLeft: <PaddingLeftIcon />,
  PaddingRight: <PaddingRightIcon />,
  PaddingTop: <PaddingTopIcon />,
  PageAdd: <PageAddIcon />,
  PageArrowRight: <PageArrowRightIcon />,
  PageCheckedin: <PageCheckedinIcon />,
  PageCheckedOut: <PageCheckedOutIcon />,
  PageData: <PageDataIcon />,
  PageEdit: <PageEditIcon />,
  PageHeaderEdit: <PageHeaderEditIcon />,
  PageHeader: <PageHeaderIcon />,
  Page: <PageIcon />,
  PageLeft: <PageLeftIcon />,
  PageLink: <PageLinkIcon />,
  PageListFilter: <PageListFilterIcon />,
  PageList: <PageListIcon />,
  PageListMirroredSolid: <PageListMirroredSolidIcon />,
  PageListSolid: <PageListSolidIcon />,
  PageLock: <PageLockIcon />,
  PageRemove: <PageRemoveIcon />,
  PageRight: <PageRightIcon />,
  PageShared: <PageSharedIcon />,
  PageSolid: <PageSolidIcon />,
  PanoIndicator: <PanoIndicatorIcon />,
  Parachute: <ParachuteIcon />,
  ParachuteSolid: <ParachuteSolidIcon />,
  Parameter: <ParameterIcon />,
  ParatureLogo: <ParatureLogoIcon />,
  ParkingLocation: <ParkingLocationIcon />,
  ParkingLocationMirrored: <ParkingLocationMirroredIcon />,
  ParkingMirroredSolid: <ParkingMirroredSolidIcon />,
  ParkingSolid: <ParkingSolidIcon />,
  PartlyCloudyDay: <PartlyCloudyDayIcon />,
  PartlyCloudyNight: <PartlyCloudyNightIcon />,
  PartyLeader: <PartyLeaderIcon />,
  PassiveAuthentication: <PassiveAuthenticationIcon />,
  PasswordField: <PasswordFieldIcon />,
  PasteAsCode: <PasteAsCodeIcon />,
  PasteAsText: <PasteAsTextIcon />,
  Paste: <PasteIcon />,
  Pause: <PauseIcon />,
  PaymentCard: <PaymentCardIcon />,
  PC1: <PC1Icon />,
  PDF: <PDFIcon />,
  PencilReply: <PencilReplyIcon />,
  Pentagon: <PentagonIcon />,
  PenWorkspace: <PenWorkspaceIcon />,
  PeopleAdd: <PeopleAddIcon />,
  PeopleAlert: <PeopleAlertIcon />,
  PeopleBlock: <PeopleBlockIcon />,
  People: <PeopleIcon />,
  PeoplePause: <PeoplePauseIcon />,
  PeopleRepeat: <PeopleRepeatIcon />,
  Permissions: <PermissionsIcon />,
  PermissionsSolid: <PermissionsSolidIcon />,
  Personalize: <PersonalizeIcon />,
  Phishing: <PhishingIcon />,
  Phone: <PhoneIcon />,
  Photo2Add: <Photo2AddIcon />,
  Photo2Fill: <Photo2FillIcon />,
  Photo2: <Photo2Icon />,
  Photo2Remove: <Photo2RemoveIcon />,
  PhotoCollection: <PhotoCollectionIcon />,
  PhotoError: <PhotoErrorIcon />,
  Photo: <PhotoIcon />,
  PhotoVideoMedia: <PhotoVideoMediaIcon />,
  PictureCenter: <PictureCenterIcon />,
  PictureFill: <PictureFillIcon />,
  Picture: <PictureIcon />,
  PictureLibrary: <PictureLibraryIcon />,
  PicturePosition: <PicturePositionIcon />,
  PictureStretch: <PictureStretchIcon />,
  PictureTile: <PictureTileIcon />,
  PieDouble: <PieDoubleIcon />,
  PieSingle: <PieSingleIcon />,
  PieSingleSolid: <PieSingleSolidIcon />,
  Pill: <PillIcon />,
  Pin: <PinIcon />,
  PinnedFill: <PinnedFillIcon />,
  Pinned: <PinnedIcon />,
  PinnedSolid: <PinnedSolidIcon />,
  PinSolid12: <PinSolid12Icon />,
  PinSolidOff12: <PinSolidOff12Icon />,
  PivotChart: <PivotChartIcon />,
  PlainText: <PlainTextIcon />,
  PlanView: <PlanViewIcon />,
  PlaybackRate1x: <PlaybackRate1xIcon />,
  PlayerSettings: <PlayerSettingsIcon />,
  Play: <PlayIcon />,
  PlayResume: <PlayResumeIcon />,
  PlayReverse: <PlayReverseIcon />,
  PlayReverseResume: <PlayReverseResumeIcon />,
  PlaySolid: <PlaySolidIcon />,
  PlugConnected: <PlugConnectedIcon />,
  PlugDisconnected: <PlugDisconnectedIcon />,
  Plug: <PlugIcon />,
  PlugSolid: <PlugSolidIcon />,
  POI: <POIIcon />,
  POISolid: <POISolidIcon />,
  PollResults: <PollResultsIcon />,
  PostUpdate: <PostUpdateIcon />,
  PowerButton: <PowerButtonIcon />,
  Precipitation: <PrecipitationIcon />,
  PresenceChickletVideo: <PresenceChickletVideoIcon />,
  Presentation12: <Presentation12Icon />,
  Presentation: <PresentationIcon />,
  Preview: <PreviewIcon />,
  PreviewLink: <PreviewLinkIcon />,
  Previous: <PreviousIcon />,
  PrimaryCalendar: <PrimaryCalendarIcon />,
  PrintfaxPrinterFile: <PrintfaxPrinterFileIcon />,
  Print: <PrintIcon />,
  ProcessingCancel: <ProcessingCancelIcon />,
  Processing: <ProcessingIcon />,
  ProcessingPause: <ProcessingPauseIcon />,
  ProcessingRun: <ProcessingRunIcon />,
  ProcessMetaTask: <ProcessMetaTaskIcon />,
  ProductCatalog: <ProductCatalogIcon />,
  Product: <ProductIcon />,
  ProductionFloorManagement: <ProductionFloorManagementIcon />,
  ProductList: <ProductListIcon />,
  ProductRelease: <ProductReleaseIcon />,
  ProductVariant: <ProductVariantIcon />,
  ProfileSearch: <ProfileSearchIcon />,
  ProFootball: <ProFootballIcon />,
  ProgressLoopInner: <ProgressLoopInnerIcon />,
  ProgressLoopOuter: <ProgressLoopOuterIcon />,
  ProgressRingDots: <ProgressRingDotsIcon />,
  ProHockey: <ProHockeyIcon />,
  PromotedDatabase: <PromotedDatabaseIcon />,
  ProtectedDocument: <ProtectedDocumentIcon />,
  ProtectRestrict: <ProtectRestrictIcon />,
  ProvisioningPackage: <ProvisioningPackageIcon />,
  PublicCalendar: <PublicCalendarIcon />,
  PublicContactCard: <PublicContactCardIcon />,
  PublicContactCardMirrored: <PublicContactCardMirroredIcon />,
  PublicEmail: <PublicEmailIcon />,
  PublicFolder: <PublicFolderIcon />,
  PublishContent: <PublishContentIcon />,
  PublishCourse: <PublishCourseIcon />,
  Puzzle: <PuzzleIcon />,
  PY: <PYIcon />,
  PythonLanguage: <PythonLanguageIcon />,
  PythonLogoBlue: <PythonLogoBlueIcon />,
  PythonLogoYellow: <PythonLogoYellowIcon />,
  QandA: <QandAIcon />,
  QandAMirror: <QandAMirrorIcon />,
  QRCode: <QRCodeIcon />,
  QuadColumn: <QuadColumnIcon />,
  Quantity: <QuantityIcon />,
  QuarterCircle: <QuarterCircleIcon />,
  QueryList: <QueryListIcon />,
  Questionnaire: <QuestionnaireIcon />,
  QuestionnaireMirrored: <QuestionnaireMirroredIcon />,
  QuickNote: <QuickNoteIcon />,
  QuickNoteSolid: <QuickNoteSolidIcon />,
  RadioBtnOff: <RadioBtnOffIcon />,
  RadioBtnOn: <RadioBtnOnIcon />,
  RadioBullet: <RadioBulletIcon />,
  Rain: <RainIcon />,
  RainShowersDay: <RainShowersDayIcon />,
  RainShowersNight: <RainShowersNightIcon />,
  RainSnow: <RainSnowIcon />,
  RawSource: <RawSourceIcon />,
  ReactLogo: <ReactLogoIcon />,
  Read: <ReadIcon />,
  ReadingMode: <ReadingModeIcon />,
  ReadingModeSolid: <ReadingModeSolidIcon />,
  ReadOutLoud: <ReadOutLoudIcon />,
  RealEstate: <RealEstateIcon />,
  ReceiptCheck: <ReceiptCheckIcon />,
  ReceiptForward: <ReceiptForwardIcon />,
  ReceiptReply: <ReceiptReplyIcon />,
  ReceiptTentative: <ReceiptTentativeIcon />,
  ReceiptTentativeMirrored: <ReceiptTentativeMirroredIcon />,
  ReceiptUndelivered: <ReceiptUndeliveredIcon />,
  Recent: <RecentIcon />,
  Record2: <Record2Icon />,
  RecruitmentManagement: <RecruitmentManagementIcon />,
  RectangleShape: <RectangleShapeIcon />,
  RectangleShapeSolid: <RectangleShapeSolidIcon />,
  RectangularClipping: <RectangularClippingIcon />,
  RecurringEvent: <RecurringEventIcon />,
  RecurringTask: <RecurringTaskIcon />,
  Redeploy: <RedeployIcon />,
  RedEye12: <RedEye12Icon />,
  RedEye: <RedEyeIcon />,
  Redo: <RedoIcon />,
  Refresh: <RefreshIcon />,
  RegistryEditor: <RegistryEditorIcon />,
  Relationship: <RelationshipIcon />,
  ReleaseDefinition: <ReleaseDefinitionIcon />,
  ReleaseGateCheck: <ReleaseGateCheckIcon />,
  ReleaseGateError: <ReleaseGateErrorIcon />,
  ReleaseGate: <ReleaseGateIcon />,
  ReminderGroup: <ReminderGroupIcon />,
  ReminderPerson: <ReminderPersonIcon />,
  ReminderTime: <ReminderTimeIcon />,
  Remote: <RemoteIcon />,
  RemoveContent: <RemoveContentIcon />,
  RemoveEvent: <RemoveEventIcon />,
  RemoveFilter: <RemoveFilterIcon />,
  RemoveFromShoppingList: <RemoveFromShoppingListIcon />,
  RemoveFromTrash: <RemoveFromTrashIcon />,
  Remove: <RemoveIcon />,
  RemoveLinkChain: <RemoveLinkChainIcon />,
  RemoveLink: <RemoveLinkIcon />,
  RemoveLinkX: <RemoveLinkXIcon />,
  RemoveOccurrence: <RemoveOccurrenceIcon />,
  Rename: <RenameIcon />,
  RenewalCurrent: <RenewalCurrentIcon />,
  RenewalFuture: <RenewalFutureIcon />,
  ReopenPages: <ReopenPagesIcon />,
  Repair: <RepairIcon />,
  RepeatAll: <RepeatAllIcon />,
  RepeatHeaderRows: <RepeatHeaderRowsIcon />,
  RepeatOne: <RepeatOneIcon />,
  ReplyAllAlt: <ReplyAllAltIcon />,
  ReplyAll: <ReplyAllIcon />,
  ReplyAllMirrored: <ReplyAllMirroredIcon />,
  ReplyAlt: <ReplyAltIcon />,
  Reply: <ReplyIcon />,
  ReplyMirrored: <ReplyMirroredIcon />,
  Repo: <RepoIcon />,
  ReportAdd: <ReportAddIcon />,
  ReportDocument: <ReportDocumentIcon />,
  ReportHacked: <ReportHackedIcon />,
  ReportLibrary: <ReportLibraryIcon />,
  ReportLibraryMirrored: <ReportLibraryMirroredIcon />,
  ReportLock: <ReportLockIcon />,
  ReportWarning: <ReportWarningIcon />,
  RepoSolid: <RepoSolidIcon />,
  Rerun: <RerunIcon />,
  ReservationOrders: <ReservationOrdersIcon />,
  ResetDevice: <ResetDeviceIcon />,
  Reset: <ResetIcon />,
  ResponsesMenu: <ResponsesMenuIcon />,
  ReturnKey: <ReturnKeyIcon />,
  ReturnToSession: <ReturnToSessionIcon />,
  ReviewRequestMirroredSolid: <ReviewRequestMirroredSolidIcon />,
  ReviewRequestSolid: <ReviewRequestSolidIcon />,
  ReviewResponseSolid: <ReviewResponseSolidIcon />,
  ReviewSolid: <ReviewSolidIcon />,
  RevToggleKey: <RevToggleKeyIcon />,
  RewindEightX: <RewindEightXIcon />,
  RewindFourX: <RewindFourXIcon />,
  Rewind: <RewindIcon />,
  RewindOneFiveX: <RewindOneFiveXIcon />,
  RewindOneX: <RewindOneXIcon />,
  RewindPointFiveX: <RewindPointFiveXIcon />,
  RewindTwoX: <RewindTwoXIcon />,
  Ribbon: <RibbonIcon />,
  RibbonSolid: <RibbonSolidIcon />,
  RightDoubleQuote: <RightDoubleQuoteIcon />,
  RightTriangle: <RightTriangleIcon />,
  Ringer: <RingerIcon />,
  RingerOff: <RingerOffIcon />,
  RingerRemove: <RingerRemoveIcon />,
  RingerSolid: <RingerSolidIcon />,
  Robot: <RobotIcon />,
  Rocket: <RocketIcon />,
  Room: <RoomIcon />,
  Rotate90Clockwise: <Rotate90ClockwiseIcon />,
  Rotate90CounterClockwise: <Rotate90CounterClockwiseIcon />,
  Rotate: <RotateIcon />,
  RowsChild: <RowsChildIcon />,
  RowsGroup: <RowsGroupIcon />,
  RubyGemsLogo: <RubyGemsLogoIcon />,
  Rugby: <RugbyIcon />,
  Running: <RunningIcon />,
  RustLanguageLogo: <RustLanguageLogoIcon />,
  Sad: <SadIcon />,
  SadSolid: <SadSolidIcon />,
  SaveAll: <SaveAllIcon />,
  SaveAndClose: <SaveAndCloseIcon />,
  SaveAs: <SaveAsIcon />,
  Save: <SaveIcon />,
  SaveTemplate: <SaveTemplateIcon />,
  SaveToMobile: <SaveToMobileIcon />,
  Savings: <SavingsIcon />,
  ScaleUp: <ScaleUpIcon />,
  ScaleVolume: <ScaleVolumeIcon />,
  ScatterChart: <ScatterChartIcon />,
  ScheduleEventAction: <ScheduleEventActionIcon />,
  ScopeTemplate: <ScopeTemplateIcon />,
  ScreenCast: <ScreenCastIcon />,
  ScreenTime: <ScreenTimeIcon />,
  Script: <ScriptIcon />,
  ScrollUpDown: <ScrollUpDownIcon />,
  SDCard: <SDCardIcon />,
  SearchAndApps: <SearchAndAppsIcon />,
  SearchBookmark: <SearchBookmarkIcon />,
  SearchCalendar: <SearchCalendarIcon />,
  SearchData: <SearchDataIcon />,
  Search: <SearchIcon />,
  SearchIssue: <SearchIssueIcon />,
  SearchIssueMirrored: <SearchIssueMirroredIcon />,
  SearchNearby: <SearchNearbyIcon />,
  SecondaryNav: <SecondaryNavIcon />,
  Section: <SectionIcon />,
  Sections: <SectionsIcon />,
  SecurityGroup: <SecurityGroupIcon />,
  SeeDo: <SeeDoIcon />,
  SelectAll: <SelectAllIcon />,
  Sell: <SellIcon />,
  SemiboldWeight: <SemiboldWeightIcon />,
  Send: <SendIcon />,
  SendMirrored: <SendMirroredIcon />,
  SentimentAnalysis: <SentimentAnalysisIcon />,
  Separator: <SeparatorIcon />,
  ServerEnviroment: <ServerEnviromentIcon />,
  Server: <ServerIcon />,
  ServerProcesses: <ServerProcessesIcon />,
  ServiceOff: <ServiceOffIcon />,
  SetAction: <SetActionIcon />,
  Settings: <SettingsIcon />,
  ShakeDevice: <ShakeDeviceIcon />,
  Shapes: <ShapesIcon />,
  ShapeSolid: <ShapeSolidIcon />,
  SharedDatabase: <SharedDatabaseIcon />,
  Share: <ShareIcon />,
  ShareiOS: <ShareiOSIcon />,
  Shirt: <ShirtIcon />,
  Shop: <ShopIcon />,
  ShoppingCart: <ShoppingCartIcon />,
  ShoppingCartSolid: <ShoppingCartSolidIcon />,
  ShopServer: <ShopServerIcon />,
  ShowGrid: <ShowGridIcon />,
  ShowResults: <ShowResultsIcon />,
  ShowResultsMirrored: <ShowResultsMirroredIcon />,
  ShowTimeAs: <ShowTimeAsIcon />,
  SidePanel: <SidePanelIcon />,
  SidePanelMirrored: <SidePanelMirroredIcon />,
  Signin: <SigninIcon />,
  SignOut: <SignOutIcon />,
  SingleBookmark: <SingleBookmarkIcon />,
  SingleBookmarkSolid: <SingleBookmarkSolidIcon />,
  SingleColumnEdit: <SingleColumnEditIcon />,
  SingleColumn: <SingleColumnIcon />,
  SIPMove: <SIPMoveIcon />,
  SiteScan: <SiteScanIcon />,
  SixPointStar: <SixPointStarIcon />,
  SizeLegacy: <SizeLegacyIcon />,
  SkipBack10: <SkipBack10Icon />,
  SkipForward30: <SkipForward30Icon />,
  SkiResorts: <SkiResortsIcon />,
  SkypeArrow: <SkypeArrowIcon />,
  SkypeCheck: <SkypeCheckIcon />,
  SkypeClock: <SkypeClockIcon />,
  SkypeMinus: <SkypeMinusIcon />,
  SliderHandleSize: <SliderHandleSizeIcon />,
  Slider: <SliderIcon />,
  SliderThumb: <SliderThumbIcon />,
  Slideshow: <SlideshowIcon />,
  SmartGlassRemote: <SmartGlassRemoteIcon />,
  SnapToGrid: <SnapToGridIcon />,
  Snooze: <SnoozeIcon />,
  Snowflake: <SnowflakeIcon />,
  Snow: <SnowIcon />,
  SnowShowerDay: <SnowShowerDayIcon />,
  SnowShowerNight: <SnowShowerNightIcon />,
  Soccer: <SoccerIcon />,
  SortDown: <SortDownIcon />,
  Sort: <SortIcon />,
  SortLinesAscending: <SortLinesAscendingIcon />,
  SortLines: <SortLinesIcon />,
  SortUp: <SortUpIcon />,
  Source: <SourceIcon />,
  Spacer: <SpacerIcon />,
  Speakers: <SpeakersIcon />,
  SpecialEvent: <SpecialEventIcon />,
  SpeedHigh: <SpeedHighIcon />,
  Spelling: <SpellingIcon />,
  Split: <SplitIcon />,
  SplitObject: <SplitObjectIcon />,
  Sprint: <SprintIcon />,
  SQLAnalyticsPool: <SQLAnalyticsPoolIcon />,
  Squalls: <SquallsIcon />,
  SquareShape: <SquareShapeIcon />,
  SquareShapeSolid: <SquareShapeSolidIcon />,
  StackColumnChart: <StackColumnChartIcon />,
  StackedBarChart: <StackedBarChartIcon />,
  StackedColumnChart2Fill: <StackedColumnChart2FillIcon />,
  StackedColumnChart2: <StackedColumnChart2Icon />,
  StackedLineChart: <StackedLineChartIcon />,
  Stack: <StackIcon />,
  StackIndicator: <StackIndicatorIcon />,
  Starburst: <StarburstIcon />,
  StarburstSolid: <StarburstSolidIcon />,
  StatusCircleBlock2: <StatusCircleBlock2Icon />,
  StatusCircleBlock: <StatusCircleBlockIcon />,
  StatusCircleCheckmark: <StatusCircleCheckmarkIcon />,
  StatusCircleErrorX: <StatusCircleErrorXIcon />,
  StatusCircleExclamation: <StatusCircleExclamationIcon />,
  StatusCircleInfo: <StatusCircleInfoIcon />,
  StatusCircleInner: <StatusCircleInnerIcon />,
  StatusCircleOuter: <StatusCircleOuterIcon />,
  StatusCircleQuestionMark: <StatusCircleQuestionMarkIcon />,
  StatusCircleRing: <StatusCircleRingIcon />,
  StatusCircleSync: <StatusCircleSyncIcon />,
  StatusErrorFull: <StatusErrorFullIcon />,
  StatusTriangleExclamation: <StatusTriangleExclamationIcon />,
  StatusTriangle: <StatusTriangleIcon />,
  StatusTriangleInner: <StatusTriangleInnerIcon />,
  StatusTriangleOuter: <StatusTriangleOuterIcon />,
  Step: <StepIcon />,
  StepInsert: <StepInsertIcon />,
  StepSharedAdd: <StepSharedAddIcon />,
  StepShared: <StepSharedIcon />,
  StepSharedInsert: <StepSharedInsertIcon />,
  StockDown: <StockDownIcon />,
  StockUp: <StockUpIcon />,
  Stop: <StopIcon />,
  StopSolid: <StopSolidIcon />,
  Stopwatch: <StopwatchIcon />,
  StorageAcount: <StorageAcountIcon />,
  StorageOptical: <StorageOpticalIcon />,
  Storyboard: <StoryboardIcon />,
  Streaming: <StreamingIcon />,
  StreamingOff: <StreamingOffIcon />,
  Street: <StreetIcon />,
  StreetsideSplitMinimize: <StreetsideSplitMinimizeIcon />,
  Strikethrough: <StrikethroughIcon />,
  Subscribe: <SubscribeIcon />,
  Subscript: <SubscriptIcon />,
  SubstitutionsIn: <SubstitutionsInIcon />,
  Suitcase: <SuitcaseIcon />,
  SunAdd: <SunAddIcon />,
  Sunny: <SunnyIcon />,
  SunQuestionMark: <SunQuestionMarkIcon />,
  Superscript: <SuperscriptIcon />,
  SurveyQuestions: <SurveyQuestionsIcon />,
  SVNLogo: <SVNLogoIcon />,
  SwiftLogo: <SwiftLogoIcon />,
  SwitcherStartEnd: <SwitcherStartEndIcon />,
  Switch: <SwitchIcon />,
  SwitchUser: <SwitchUserIcon />,
  SyncFolder: <SyncFolderIcon />,
  Sync: <SyncIcon />,
  SyncOccurence: <SyncOccurenceIcon />,
  SyncStatus: <SyncStatusIcon />,
  SyncStatusSolid: <SyncStatusSolidIcon />,
  SyncToPC: <SyncToPCIcon />,
  System: <SystemIcon />,
  TabCenter: <TabCenterIcon />,
  Tab: <TabIcon />,
  TableBrandedColumn: <TableBrandedColumnIcon />,
  TableBrandedRow: <TableBrandedRowIcon />,
  TableComputed: <TableComputedIcon />,
  TableFirstColumn: <TableFirstColumnIcon />,
  TableGroup: <TableGroupIcon />,
  TableHeaderRow: <TableHeaderRowIcon />,
  Table: <TableIcon />,
  TableLastColumn: <TableLastColumnIcon />,
  TableLink: <TableLinkIcon />,
  Tablet: <TabletIcon />,
  TabletMode: <TabletModeIcon />,
  TableTotalRow: <TableTotalRowIcon />,
  TabletSelected: <TabletSelectedIcon />,
  TabOneColumn: <TabOneColumnIcon />,
  TabThreeColumn: <TabThreeColumnIcon />,
  TabTwoColumn: <TabTwoColumnIcon />,
  TagGroup: <TagGroupIcon />,
  Tag: <TagIcon />,
  TagSolid: <TagSolidIcon />,
  TagUnknown12: <TagUnknown12Icon />,
  TagUnknown12Mirror: <TagUnknown12MirrorIcon />,
  TagUnknown: <TagUnknownIcon />,
  TagUnknownMirror: <TagUnknownMirrorIcon />,
  Taskboard: <TaskboardIcon />,
  TaskGroup: <TaskGroupIcon />,
  TaskGroupMirrored: <TaskGroupMirroredIcon />,
  TaskList: <TaskListIcon />,
  TaskManager: <TaskManagerIcon />,
  TaskManagerMirrored: <TaskManagerMirroredIcon />,
  TaskSolid: <TaskSolidIcon />,
  Taxi: <TaxiIcon />,
  TeamFavorite: <TeamFavoriteIcon />,
  Teamwork: <TeamworkIcon />,
  Teeth: <TeethIcon />,
  Telemarketer: <TelemarketerIcon />,
  TemporaryUser: <TemporaryUserIcon />,
  Tennis: <TennisIcon />,
  TestAutoSolid: <TestAutoSolidIcon />,
  TestBeaker: <TestBeakerIcon />,
  TestBeakerSolid: <TestBeakerSolidIcon />,
  TestCase: <TestCaseIcon />,
  TestExploreSolid: <TestExploreSolidIcon />,
  TestImpactSolid: <TestImpactSolidIcon />,
  TestParameter: <TestParameterIcon />,
  TestPlan: <TestPlanIcon />,
  TestStep: <TestStepIcon />,
  TestSuite: <TestSuiteIcon />,
  TestUserSolid: <TestUserSolidIcon />,
  TextAlignBottom: <TextAlignBottomIcon />,
  TextAlignMiddle: <TextAlignMiddleIcon />,
  TextAlignTop: <TextAlignTopIcon />,
  TextBox: <TextBoxIcon />,
  TextCallout: <TextCalloutIcon />,
  TextDocumentEdit: <TextDocumentEditIcon />,
  TextDocument: <TextDocumentIcon />,
  TextDocumentSettings: <TextDocumentSettingsIcon />,
  TextDocumentShared: <TextDocumentSharedIcon />,
  TextField: <TextFieldIcon />,
  TextOverflow: <TextOverflowIcon />,
  TextParagraphOption: <TextParagraphOptionIcon />,
  TextRecognition: <TextRecognitionIcon />,
  TextRotate270Degrees: <TextRotate270DegreesIcon />,
  TextRotate90Degrees: <TextRotate90DegreesIcon />,
  TextRotateHorizontal: <TextRotateHorizontalIcon />,
  TextRotation: <TextRotationIcon />,
  ThisPC: <ThisPCIcon />,
  ThreeQuarterCircle: <ThreeQuarterCircleIcon />,
  ThumbnailView: <ThumbnailViewIcon />,
  ThumbnailViewMirrored: <ThumbnailViewMirroredIcon />,
  Thunderstorms: <ThunderstormsIcon />,
  Ticket: <TicketIcon />,
  Tiles2: <Tiles2Icon />,
  Tiles: <TilesIcon />,
  TimeEntry: <TimeEntryIcon />,
  TimelineDelivery: <TimelineDeliveryIcon />,
  Timeline: <TimelineIcon />,
  TimelineMatrixView: <TimelineMatrixViewIcon />,
  TimelineProgress: <TimelineProgressIcon />,
  TimePicker: <TimePickerIcon />,
  Timer: <TimerIcon />,
  TimeSheet: <TimeSheetIcon />,
  ToggleBorder: <ToggleBorderIcon />,
  ToggleFilled: <ToggleFilledIcon />,
  ToggleLeft: <ToggleLeftIcon />,
  ToggleRight: <ToggleRightIcon />,
  ToggleThumb: <ToggleThumbIcon />,
  Toll: <TollIcon />,
  Toolbox: <ToolboxIcon />,
  Total: <TotalIcon />,
  Touch: <TouchIcon />,
  TouchPointer: <TouchPointerIcon />,
  Trackers: <TrackersIcon />,
  TrackersMirrored: <TrackersMirroredIcon />,
  Train: <TrainIcon />,
  TrainSolid: <TrainSolidIcon />,
  TransferCall: <TransferCallIcon />,
  TransitionEffect: <TransitionEffectIcon />,
  Transition: <TransitionIcon />,
  TransitionPop: <TransitionPopIcon />,
  TransitionPush: <TransitionPushIcon />,
  Translate: <TranslateIcon />,
  Trending12: <Trending12Icon />,
  TriangleDown12: <TriangleDown12Icon />,
  TriangleLeft12: <TriangleLeft12Icon />,
  TriangleRight12: <TriangleRight12Icon />,
  TriangleShape: <TriangleShapeIcon />,
  TriangleShapeSolid: <TriangleShapeSolidIcon />,
  TriangleSolidDown12: <TriangleSolidDown12Icon />,
  TriangleSolid: <TriangleSolidIcon />,
  TriangleSolidLeft12: <TriangleSolidLeft12Icon />,
  TriangleSolidRight12: <TriangleSolidRight12Icon />,
  TriangleSolidUp12: <TriangleSolidUp12Icon />,
  TriangleUp12: <TriangleUp12Icon />,
  TriggerApproval: <TriggerApprovalIcon />,
  TriggerAuto: <TriggerAutoIcon />,
  TriggerUser: <TriggerUserIcon />,
  TrimEnd: <TrimEndIcon />,
  Trim: <TrimIcon />,
  TrimStart: <TrimStartIcon />,
  TripleColumnEdit: <TripleColumnEditIcon />,
  TripleColumn: <TripleColumnIcon />,
  TripleColumnWide: <TripleColumnWideIcon />,
  Trophy2: <Trophy2Icon />,
  Trophy2Solid: <Trophy2SolidIcon />,
  Trophy: <TrophyIcon />,
  TurnRight: <TurnRightIcon />,
  TVMonitor: <TVMonitorIcon />,
  TVMonitorSelected: <TVMonitorSelectedIcon />,
  TwelvePointStar: <TwelvePointStarIcon />,
  TwitterLogo: <TwitterLogoIcon />,
  Umbrella: <UmbrellaIcon />,
  Underline: <UnderlineIcon />,
  Undo: <UndoIcon />,
  Uneditable2: <Uneditable2Icon />,
  Uneditable2Mirrored: <Uneditable2MirroredIcon />,
  Uneditable: <UneditableIcon />,
  UneditableMirrored: <UneditableMirroredIcon />,
  UneditableSolid12: <UneditableSolid12Icon />,
  UneditableSolidMirrored12: <UneditableSolidMirrored12Icon />,
  Unfavorite: <UnfavoriteIcon />,
  UngroupObject: <UngroupObjectIcon />,
  UnknownCall: <UnknownCallIcon />,
  Unknown: <UnknownIcon />,
  UnknownMirrored: <UnknownMirroredIcon />,
  UnknownMirroredSolid: <UnknownMirroredSolidIcon />,
  UnknownSolid: <UnknownSolidIcon />,
  Unlock: <UnlockIcon />,
  UnlockSolid: <UnlockSolidIcon />,
  Unpin: <UnpinIcon />,
  UnpublishContent: <UnpublishContentIcon />,
  UnSetColor: <UnSetColorIcon />,
  UnstackSelected: <UnstackSelectedIcon />,
  Unsubscribe: <UnsubscribeIcon />,
  UnsyncFolder: <UnsyncFolderIcon />,
  UnsyncOccurence: <UnsyncOccurenceIcon />,
  Untag: <UntagIcon />,
  UpdateRestore: <UpdateRestoreIcon />,
  UpgradeAnalysis: <UpgradeAnalysisIcon />,
  Up: <UpIcon />,
  Upload: <UploadIcon />,
  URLBlock: <URLBlockIcon />,
  USB: <USBIcon />,
  UserEvent: <UserEventIcon />,
  UserFollowed: <UserFollowedIcon />,
  UserGauge: <UserGaugeIcon />,
  UserOptional: <UserOptionalIcon />,
  UserPause: <UserPauseIcon />,
  UserRemove: <UserRemoveIcon />,
  UserSync: <UserSyncIcon />,
  UserWarning: <UserWarningIcon />,
  Vacation: <VacationIcon />,
  Vaccination: <VaccinationIcon />,
  Variable2: <Variable2Icon />,
  VariableGroup: <VariableGroupIcon />,
  Variable: <VariableIcon />,
  VB: <VBIcon />,
  VennDiagram: <VennDiagramIcon />,
  VerifiedBrand: <VerifiedBrandIcon />,
  VerifiedBrandSolid: <VerifiedBrandSolidIcon />,
  VersionControlPush: <VersionControlPushIcon />,
  VerticalDistributeCenter: <VerticalDistributeCenterIcon />,
  Video360Generic: <Video360GenericIcon />,
  Video: <VideoIcon />,
  VideoLightOff: <VideoLightOffIcon />,
  VideoOff2: <VideoOff2Icon />,
  VideoOff: <VideoOffIcon />,
  VideoSearch: <VideoSearchIcon />,
  VideoSolid: <VideoSolidIcon />,
  ViewAll2: <ViewAll2Icon />,
  ViewAll: <ViewAllIcon />,
  ViewDashboard: <ViewDashboardIcon />,
  View: <ViewIcon />,
  ViewInAR: <ViewInARIcon />,
  ViewListGroup: <ViewListGroupIcon />,
  ViewList: <ViewListIcon />,
  ViewListTree: <ViewListTreeIcon />,
  ViewOriginal: <ViewOriginalIcon />,
  VisuallyImpaired: <VisuallyImpairedIcon />,
  VisualsFolder: <VisualsFolderIcon />,
  VisualsStore: <VisualsStoreIcon />,
  VoicemailForward: <VoicemailForwardIcon />,
  VoicemailIRM: <VoicemailIRMIcon />,
  VoicemailReply: <VoicemailReplyIcon />,
  Volume0: <Volume0Icon />,
  Volume1: <Volume1Icon />,
  Volume2: <Volume2Icon />,
  Volume3: <Volume3Icon />,
  VolumeDisabled: <VolumeDisabledIcon />,
  Waffle: <WaffleIcon />,
  WaitlistConfirm: <WaitlistConfirmIcon />,
  WaitlistConfirmMirrored: <WaitlistConfirmMirroredIcon />,
  Warning12: <Warning12Icon />,
  Warning: <WarningIcon />,
  WarningSolid: <WarningSolidIcon />,
  WavingHand: <WavingHandIcon />,
  Webcam2: <Webcam2Icon />,
  Webcam2Off: <Webcam2OffIcon />,
  WebComponents: <WebComponentsIcon />,
  WebEnvironment: <WebEnvironmentIcon />,
  WebPublish: <WebPublishIcon />,
  Website: <WebsiteIcon />,
  WebTemplate: <WebTemplateIcon />,
  Weights: <WeightsIcon />,
  Wheelchair: <WheelchairIcon />,
  WifiEthernet: <WifiEthernetIcon />,
  WifiWarning4: <WifiWarning4Icon />,
  WindDirection: <WindDirectionIcon />,
  WindowEdit: <WindowEditIcon />,
  Wines: <WinesIcon />,
  WipePhone: <WipePhoneIcon />,
  WorkFlow: <WorkFlowIcon />,
  WorkforceManagement: <WorkforceManagementIcon />,
  Work: <WorkIcon />,
  WorkItemAlert: <WorkItemAlertIcon />,
  WorkItemBar: <WorkItemBarIcon />,
  WorkItemBarSolid: <WorkItemBarSolidIcon />,
  WorkItemBug: <WorkItemBugIcon />,
  WorkItem: <WorkItemIcon />,
  WorldClock: <WorldClockIcon />,
  World: <WorldIcon />,
  XamarinLogo: <XamarinLogoIcon />,
  XboxController: <XboxControllerIcon />,
  ZipFolder: <ZipFolderIcon />,
  Zoom: <ZoomIcon />,
  ZoomIn: <ZoomInIcon />,
  ZoomOut: <ZoomOutIcon />,
  ZoomToFit: <ZoomToFitIcon />,
}
