name: Snyk Security Vulnerability Scan

on:
  pull_request:
    types: [opened, edited, synchronize]
  push:
    tags:
      - 'v.[0-9].[0-100]+.[0-100]+'
    branches:
      - main
      - devops/snyk-integration

jobs:
  snyk_scan_test:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: snyk/actions/setup@master
      
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Snyk scan for Node dependencies - 'package.json' files
        continue-on-error: true
        run: |
          find . -name 'package.json' | while read file; do
            dir=$(dirname "$file")
            (cd "$dir" && npm install && snyk test --file=package.json -d --fail-on=all)
          done
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      
      - name: Snyk scan for Node dependencies - 'package-lock.json' files
        continue-on-error: true
        run: |
          find . -name 'package-lock.json' | while read file; do
            dir=$(dirname "$file")
            (cd "$dir" && npm install && snyk test --file=package-lock.json -d --fail-on=all)
          done
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'

      - name: Snyk scan for Python dependencies - 'requirements.txt' files
        run: |
          find . -name 'requirements.txt' | while read file; do
            dir=$(dirname "$file")
            (cd "$dir" && pip install -r requirements.txt && snyk test command=python3 --package-manager=pip --file=requirements.txt --skip-unresolved -d --fail-on=all)
          done
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      

  snyk_scan_monitor:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Extract github branch/tag name
        shell: bash
        run: echo "ref=$(echo ${GITHUB_REF##*/})" >> $GITHUB_OUTPUT
        id: extract_re

      - uses: snyk/actions/setup@master
      
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'

      - name: Snyk scan for Python dependencies - 'requirements.txt' files
        run: |
          export BRANCH_TAG_NAME=${{ steps.extract_ref.outputs.ref }}
          for file in $(find . -name "requirements.txt"); do
            file=${file:2}
            echo ""
            echo "##### SCAN $file START #####"
            echo ""
            pip install -r $file
            snyk monitor --package-manager=pip --org=nitro-cf8 --remote-repo-url=nitro-cf8/$BRANCH_TAG_NAME --file=$file --project-name=NITRO/nitro/$BRANCH_TAG_NAME/$file -d --skip-unresolved 
            echo "##### SCAN $file END #####"
          done
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      
