name: Snyk Security Vulnerability Scan

on:
  pull_request:
    types: [opened, edited, synchronize]
  push:
    tags:
      - 'v.[0-9].[0-100]+.[0-100]+'
    branches:
      - main
      - devops/snyk-integration

jobs:
  snyk_scan_test:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: snyk/actions/setup@master
      
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Snyk scan for Node dependencies - 'package.json' files
        continue-on-error: true
        run: |
          find . -name 'package.json' | xargs -I {} sh -c 'cd "$(dirname "{}")" && npm install && snyk test --file="$(basename "{}")" -d --fail-on=all'
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      
      - name: Snyk scan for Node dependencies - 'package-lock.json' files
        continue-on-error: true
        run: |
          find . -name 'package-lock.json' | xargs -I {} sh -c 'cd "$(dirname "{}")" && npm install && snyk test --file="$(basename "{}")" -d --fail-on=all'
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  snyk_scan_monitor:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Extract github branch/tag name
        shell: bash
        run: echo "ref=$(echo ${GITHUB_REF##*/})" >> $GITHUB_OUTPUT
        id: extract_re

      - uses: snyk/actions/setup@master
      
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Snyk scan for Node dependencies - 'package.json' files
        continue-on-error: true
        run: |
          find . -name 'package.json' | xargs -I {} sh -c 'cd "$(dirname "{}")" && npm install && snyk monitor --file="$(basename "{}")" -d  --org=NITRO-CF8 --remote-repo-url=nitro/${{ steps.extract_ref.outputs.ref }} --project-name=NITRO/nitro/${{ steps.extract_ref.outputs.ref }}/"$(basename "{}")"'
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      
      - name: Snyk scan for Node dependencies - 'package-lock.json' files
        continue-on-error: true
        run: |
          find . -name 'package-lock.json' | xargs -I {} sh -c 'cd "$(dirname "{}")" && npm install && snyk monitor --file="$(basename "{}")" -d  --org=NITRO-CF8 --remote-repo-url=nitro/${{ steps.extract_ref.outputs.ref }} --project-name=NITRO/nitro/${{ steps.extract_ref.outputs.ref }}/"$(basename "{}")"'
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
