name: Snyk Security Vulnerability Scan

on:
  pull_request:
    types: [opened, edited, synchronize]
  push:
    tags:
      - 'v.[0-9].[0-100]+.[0-100]+'
    branches:
      - main
      - devops/snyk-integration

jobs:
  snyk_scan_test:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: snyk/actions/setup@master
      
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Snyk scan for Node dependencies
        continue-on-error: true
        run: |
          find /path/to/directory -type f -regex "package(-lock)?\.json" -exec sh -c 'snyk test --file="$0" -d fail-on=all' {} \;
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  # snyk_scan_monitor:
  #   if: ${{ github.event_name == 'push' }}
  #   runs-on: ubuntu-latest
  #   steps:
